### ISSUE TITLE
Laravel 5.5 still errors with 1.24.1 patch upgrade

### ISSUE THREAD

**Issue by trwilliams** [briannesbitt/Carbon#1174] opened 2018-03-09 16:10 UTC
Declaration of Illuminate\Support\Carbon::__set_state(array $array) should be compatible with Carbon\Carbon::__set_state($state)

**Comment by sambenne** [comment] 2018-03-09 16:13
I am getting this with Laravel v5.6.10 on PHP 7.2.3

**Comment by 36864** [comment] 2018-03-09 16:14
This is already being handled. Laravel tagged a fix, and Carbon reverted the change so now the problem is still there, just reversed.

**Comment by mike-code** [comment] 2018-03-09 16:16
lmao, laravel fixed it's issue so now it's broken again

**Comment by artemirq** [comment] 2018-03-09 16:16
+1 guys

**Comment by RobinBertilsson** [comment] 2018-03-09 16:18
Pew, makes me so happy to see that other than me having this problem.
I created a new project like a week ago, that worked fine, and today when i tried creating another project i got this error.

Do we have any perspective on when this is fixed?

**Comment by sairam2188** [comment] 2018-03-09 16:31
+1
Laravel 5.5.37
Error on composer update

**Comment by kylekatarnls** [comment] 2018-03-09 16:32
Waiting for this to be merged: https://github.com/laravel/framework/pull/23464

**Closed by kylekatarnls** 2018-03-09 16:32 UTC
