### ISSUE TITLE
CarbonInterval serialization up to microseconds

### ISSUE THREAD

**Issue by rela589n** [briannesbitt/Carbon#2470] opened 2021-10-04 09:20 UTC
Hello,

I encountered an issue with the following code:
```php
var_dump(unserialize(serialize(CarbonInterval::minutes(1)->subMicroseconds(1)))->totalMicroseconds);
var_dump(CarbonInterval::minutes(1)->subMicroseconds(1)->totalMicroseconds);
```

Carbon version: **2.51.1**

PHP version: **8.0.9**

I expected to get:

```
int(59999999)
int(59999999)
```

But I actually get:

```
int(59000000)
int(59999999)
```

Thanks!

**Comment by kylekatarnls** [comment] 2021-10-04 11:22
Hello 👋 

This sounds like a regression in PHP since PHP 7.3.14 / 7.4.2:
https://3v4l.org/oPMSB

I don't think there is much we can do to fix this from Carbon side, you can try to use `->cascade()` before serialization, but it would lead to precision loss for interval bigger than 4 weeks.

**Comment by kylekatarnls** [comment] 2021-10-04 11:29
Bug reported to PHP team: https://bugs.php.net/bug.php?id=81500

**Comment by kylekatarnls** [comment] 2021-10-31 16:46
This will be fixed PHP side: https://github.com/php/php-src/pull/7575
See result with master branch: https://3v4l.org/98QjA/rfc#vgit.master

The regression happen in all of those versions:
7.3.13 ->7.3. 14
7.4.1 -> 7.4.2
All 8.0 and 8.1

**Closed by kylekatarnls** 2021-10-31 16:46 UTC
Labels: php bug
