### ISSUE TITLE
1.37 AddMinute Method not found

### ISSUE THREAD

**Issue by Yo1L** [briannesbitt/Carbon#1709] opened 2019-05-03 09:45 UTC
Hello,

I encountered an issue with the following code:
```php
echo Carbon::now()->addMinute(30);
```

Carbon version: 1.37

PHP version: 7.2.10-0ubuntu0.18.04.1

I expected to get:

```
Date of the day + 30 minutes
```

But I actually get:

```
Exception: AddMinute method not found
```

There is no issue with prior versions like 1.36.2

Thanks!

**Comment by mariosvasiliou** [comment] 2019-05-03 09:54
The latest update broke Laravel application is not even booting. Laravel 5.5
I think is the "if" in macro that was added and "continue;"

**Comment by robinnydahl** [comment] 2019-05-03 10:01
I suggest you downgrade as a temporary fix until the issue is resolved:
```
composer require nesbot/carbon:1.36.2
```


This issue is a duplicate of #1708

**Comment by webstylecenter** [comment] 2019-05-03 10:25
Same goes for AddSeconds(). Noticed this bug using OctoberCMS

**Comment by kylekatarnls** [comment] 2019-05-03 13:02
Duplicateur #1708

**Closed by kylekatarnls** 2019-05-03 13:02 UTC

**Comment by kylekatarnls** [comment] 2019-05-03 13:29
Run `composer update` to get 1.37.1.
