### ISSUE TITLE
TranslatorStrongType/TranslatorWeakType does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by nickurt** [briannesbitt/Carbon#2512] opened 2021-12-03 10:09 UTC
```sh
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading nesbot/carbon (2.55.0)
  - Upgrading nesbot/carbon (2.54.0 => 2.55.0): Extracting archive

Generating optimized autoload files
Class Carbon\Translator located in ./vendor/nesbot/carbon/src/Carbon/TranslatorStrongType.php does not comply with psr-4 autoloading standard. Skipping.
Class Carbon\Translator located in ./vendor/nesbot/carbon/src/Carbon/TranslatorWeakType.php does not comply with psr-4 autoloading standard. Skipping.
````

**Comment by brainiac84** [comment] 2021-12-03 10:14
same here

**Comment by andriesreitsma** [comment] 2021-12-03 10:42
This also creates an issue with `symfony/translation` as the declaration of the function **trans()** within `TranslatorWeakType.php` is not compatible with the loaded package. Downgrading `symfony/translation` from `v6.0.0` to `v5.4.0` solves this temporarily.

```
Whoops\Exception\ErrorException

  Declaration of Carbon\Translator::trans($id, array $parameters = [], $domain = null, $locale = null) must be compatible with Symfony\Component\Translation\Translator::trans(?string $id, array $parameters = [], ?string $domain = null, ?string $locale = null): string

  at vendor/nesbot/carbon/src/Carbon/TranslatorWeakType.php:27
```

**Comment by ngoyal16** [comment] 2021-12-03 12:24
In Localization.php line 696:

Class 'Carbon\Translator' not found

**Comment by stanimirdim92** [comment] 2021-12-03 12:40
Using nesbot/carbon 2.54 solved the problem for me. Only version 2.55 and above has this problem. 

However, a permanent fix is needed.

**Comment by kylekatarnls** [comment] 2021-12-03 12:49
Hello, we're mixing different things into this issue:

`does not comply with psr-4 autoloading standard. Skipping.`

is just a notice. We're aware of this, we made this to unlock installation with Symfony 6.

Installations are checked by CI and the installation of 2.55.0 should be possible whatever the version of Symfony you maye have  2.54 and below can't be installed with Symfony 6.

CI runs on Composer 2, so if you have a blocking error with Composer 2, please check you don't have incompatible version in the composer.lock file.

If you still have installation blocked after a clean install, please follow the issue template, provide steps to reproduce it with your exact versions of PHP, composer, Carbon and relevant dependencies and the exact command you run.

**Comment by kylekatarnls** [comment] 2021-12-03 13:03
Can you try to `composer require nesbot/carbon:dev-fix/translator-out`? If you can confirm it helps, I will release this patch as `2.55.1`

**Comment by andriesreitsma** [comment] 2021-12-03 13:27
> Can you try to `composer require nesbot/carbon:dev-fix/translator-out`? If you can confirm it helps, I will release this patch as `2.55.1`

When checking out that branch, a `composer du` completes without failure, heading back to the `2.55.0` release the error is back when doing composer dump autoload. Haven't been able to check functionality though, so have to do that now.

**Comment by nickurt** [comment] 2021-12-03 13:33
The 'does not comply with psr-4 autoloading standard' messages are gone with the changes in that branch, while doing ```composer dump-autoload```

**Comment by andriesreitsma** [comment] 2021-12-03 13:41
@kylekatarnls the `Ambiguous class resolution, "Carbon\Translator"` is also gone and functionality still seems to be in order, so I can confirm that for `composer 1.10.23` this issue has been resolved by the purposed fix. Maybe an execution of a function/test to fully confirm should be necessary?

**Closed** 2021-12-03 13:47 UTC

**Comment by kylekatarnls** [comment] 2021-12-03 13:56
2.55.1 released, still work as expected in both my Laravel and Symfony apps.
