### ISSUE TITLE
diffInSeconds broken after PHP 7.2.12 release

### ISSUE THREAD

**Issue by driesvints** [briannesbitt/Carbon#1503] opened 2018-11-12 15:33 UTC
Hello,

I encountered an issue with the following code:

```php
$now = Carbon::now();

// some milliseconds pass.

echo Carbon::now()->diffInSeconds($now, false);
```
Carbon version: **1.34.1**
PHP version: **7.2.12**

I expected to get:

```
0
```

But I actually get:

```
A much higher number (differs depending on how much milliseconds have passed).
```

I believe this is because https://bugs.php.net/bug.php?id=77007 was merged for 7.2.12 causing differences between these versions. I'm not sure how this should be solved.

**Comment by driesvints** [comment] 2018-11-12 15:36
At the moment builds on laravel/framework are failing because of the above issue: https://travis-ci.org/laravel/framework/jobs/453254179

I've traced it down to this method where the `diffInSeconds` call is made: https://github.com/laravel/framework/blob/5.7/src/Illuminate/Cache/Repository.php#L563-L572

I've already tried replacing the `Carbon::createFromTimestamp($duration->getTimestamp())` call by just passing the `$duration` instance (which should be fine in theory) but without luck.

**Comment by kylekatarnls** [comment] 2018-11-12 15:38
I tried the following:

```php
$now = Carbon::now();

usleep(500000);

echo Carbon::now()->diffInSeconds($now, false);
```

And get 0 or -1, so this seems OK.

Could you add some sample of output with diffInSeconds and the exact difference for this output using:
```php
echo Carbon::now()->diffInSeconds($now, false);
echo "\n\n";
echo Carbon::now()->format('U.u') - $now->format('U.u');
```

**Comment by kylekatarnls** [comment] 2018-11-12 15:40
Note: we also noted PHP 7.2 started to fail yesterday on our Laravel+Carbon unit tests:
https://travis-ci.org/kylekatarnls/carbon-laravel/builds/453545395

Probably related.

**Comment by kylekatarnls** [comment] 2018-11-12 15:46
https://bugs.php.net/bug.php?id=77007 is a very big problem for us and the way we handle difference. It clearly can be the root cause.

I'm a bit exhausted of the breaking patches of the PHP DateTime API. I will try to create a work-around.

**Comment by driesvints** [comment] 2018-11-12 15:48
@kylekatarnls feeling you man. Thanks for looking into this and helping out. Really appreciating it 👍

**Comment by driesvints** [comment] 2018-11-12 15:49
Any chance we can solve this in a way so people on <7.2.12 aren't left in the dark? If I can help out in any way please let me know.

**Comment by kylekatarnls** [comment] 2018-11-12 16:14
Should be painless using some "if microseconds are negative", I will fix diffInSeconds (will inherit to Minutes/Hours, etc.) and diffAsCarbonInterval. `diff()` method will remains the native PHP method and so will have the bug of negative microseconds when PHP has it.

I will patch 1.34 and 2.5 only with this work-around.

**Comment by kylekatarnls** [comment] 2018-11-12 16:34
There are collateral damages https://travis-ci.org/kylekatarnls/Carbon/builds/454054918

So diffAsCarbonInterval fix will be part of a next minor released of  Carbon 2 but not integrated in a patch. I will only fix diffInSeconds for now.

**Comment by kylekatarnls** [comment] 2018-11-12 16:43
This is not a collateral damage, something changed really badly in PHP 7.2.12 and 7.3.0RC5 (so versions of the 8 november). Have to inspect deeper the common changes of those both versions.

**Comment by driesvints** [comment] 2018-11-12 18:18
@kylekatarnls I managed to make our tests pass with the following adjustments:

```php

    public function diffInSeconds($date = null, $absolute = true)
    {
        $diff = $this->resolveCarbon($date)->diff($this);
        $value = ($diff->days * static::HOURS_PER_DAY * static::MINUTES_PER_HOUR * static::SECONDS_PER_MINUTE) +
            ($diff->h * static::MINUTES_PER_HOUR * static::SECONDS_PER_MINUTE) +
            ($diff->i * static::SECONDS_PER_MINUTE) +
            ($diff->s) - ($diff->f < 0 ? 1 : 0);

        return $absolute || !$diff->invert ? -$value : $value;
    }
```

Basically invert the `diff` call and swap the negation at the end. I don't know what the impact of this and the `absolute` flag is?

**Comment by driesvints** [comment] 2018-11-12 18:20
This also works and probably makes more sense:

```
    public function diffInSeconds($date = null, $absolute = true)
    {
        $diff = $this->resolveCarbon($date)->diff($this);
        $value = ($diff->days * static::HOURS_PER_DAY * static::MINUTES_PER_HOUR * static::SECONDS_PER_MINUTE) +
            ($diff->h * static::MINUTES_PER_HOUR * static::SECONDS_PER_MINUTE) +
            ($diff->i * static::SECONDS_PER_MINUTE) +
            ($diff->s) - ($diff->f < 0 ? 1 : 0);

        return $absolute || $diff->invert ? $value : -$value;
    }
```

**Comment by kylekatarnls** [comment] 2018-11-12 18:42
We will certainly not invert the result, this is a breaking change.

This is what we currently expect when $absolute is false:
```php
$dt = Carbon::createFromDate(2000, 1, 1);
$this->assertSame(-58, $dt->diffInSeconds($dt->copy()->subMinute()->addSeconds(2), false));
```

`- ($diff->f < 0 ? 1 : 0)` is what I added to fix it but I will carefully check different cases before releasing the patch.

**Comment by kylekatarnls** [comment] 2018-11-12 22:50
Hi,

Could you try 1.34.2 if all is fine to pass your tests?

Thanks

**Comment by driesvints** [comment] 2018-11-13 09:29
@kylekatarnls the tests pass though if I use the `diffInRealSeconds` method. Think we might use this instead in the meantime.

**Comment by kylekatarnls** [comment] 2018-11-13 09:47
diffInRealSeconds typically succeed when DST causes trouble in DateInterval, that's why, on upgrading to Carbon 2 in Laravel 5.8, I advised to use it for differences like cookies expirations, cache TTL, etc.

Basically, diffInSeconds compute DateInterval properties (based on calendar), while diffInRealSeconds use timestamps (so based on UTC timing).

Replacing it seems appropriate for your cache feature.

**Comment by driesvints** [comment] 2018-11-13 09:48
Okay! Thanks for all your help @kylekatarnls. Really appreciating it 👍

**Comment by kylekatarnls** [comment] 2018-11-13 09:50
You're welcome, we really appreciate Laravel too ! And I enjoy using it for a lot of my personal projects.

**Comment by kylekatarnls** [comment] 2018-11-13 12:36
I sadly have to re-open this issue as this has revealed an other PHP divergence between patches we have to handle too:

```php
<?php

$s = new DateTime('2018-10-11 20:59:06.914653');
$e = new DateTime('2018-10-11 20:59:06.237419');

echo $s->diff($e)->format('%R %Y-%M-%D %H:%I:%S.%F');
```

Output for 7.3.0rc4 - 7.3.0rc5
```
+ -1-11-29 23:59:59.322766
```
Output for 7.1.0 - 7.3.0rc3
```
+ 00-00-00 00:00:00.-677234
```
Output for 5.6.38 - 7.0.32
```
+ 00-00-00 00:00:00.%F
```

https://3v4l.org/hnnL0

**Comment by kylekatarnls** [comment] 2018-11-13 12:47
Opened new ticket on PHP bug tracker: https://bugs.php.net/bug.php?id=77145

**Comment by kylekatarnls** [comment] 2018-11-14 12:54
More precise support done in 1.35.0 and 2.5.3. Now to detect faster those breaking patches, I opened an other issue: https://github.com/briannesbitt/Carbon/issues/1511

**Closed by kylekatarnls** 2018-11-14 12:54 UTC

**Comment by mkopinsky** [comment] 2018-11-15 22:44
There is still a breaking change from 1.34.1 to 1.35.0.

test.php:
```php
<?php
use Carbon\Carbon;
require 'vendor/autoload.php';

Carbon::setTestNow('2019-01-01 01:23:45.6789');

$d1 = Carbon::now();
$d2 = Carbon::parse((string) $d1)->addSeconds(2);
var_dump($d1);
var_dump($d2);
var_dump($d2->diffInSeconds($d1));
```

In 1.34.1 (and earlier), the `diffInSeconds()` returns 2. From 1.34.2 and later it returns 1. In fairness, I'm not sure what the "correct" answer is given that the true diff is ~1.35 seconds, but ultimately this is a breaking change.

**Comment by mkopinsky** [comment] 2018-11-16 15:19
That makes total sense. Never thought *I* would be That Guy in the classic XKCD:

![Relevant XKCD](https://imgs.xkcd.com/comics/workflow.png)

In our case we weren't explicitly casting $d2 to a string, we were saving it to MySQL as a datetime, and then (skipping a number of steps that actually made this valuable in our context) doing an assertion that depended on the diffInSeconds() in the database-stored time and the diffInSeconds() on the time in memory to match. This is really an edge case in a unit test, which I will now fix by adding ->startOfSecond() to the `Carbon::setTestNow()` at the top of the script.

Thanks for the explanation!

**Comment by kylekatarnls** [comment] 2018-11-16 15:48
You may be interested in the following possibilities:
- You can set precision to 6 in MySQL to save datetime with microseconds, so you will no longer lost microseconds precision on database save/restore.
- You can use `->startOfSecond()` before diff calculation to force a second-rounding.

**Comment by sullyfischer** [comment] 2019-04-19 10:49
@kylekatarnls your solution solved it for me. thank you
