### ISSUE TITLE
'today' is not is not affected by setTestNow

### ISSUE THREAD

**Issue by a300600st** [briannesbitt/Carbon#951] opened 2017-05-19 18:00 UTC
```
Carbon::setTestNow(Carbon::parse('2017-03-03'));
echo Carbon::now(); // 2017-03-03 00:00:00.000000
echo Carbon::parse('today'): // 2017-05-19 00:00:00.000000
```

It's not listed in the [docs](http://carbon.nesbot.com/docs/#api-testing) either so I'm curious if this is intentional.

**Comment by kylekatarnls** [comment] 2018-02-28 16:24
Indeed, we should need exceptions for parse relative to now arguments. It would be relevant for the setTestNow purpose (testing).

**Comment by kylekatarnls** [comment] 2018-02-28 16:45
Duplicate of #940 please continue the discussion on it.

**Closed by kylekatarnls** 2018-02-28 16:45 UTC
