### ISSUE TITLE
DateDiff Return an unexpected result on leap years

### ISSUE THREAD

**Issue by jcerrada** [briannesbitt/Carbon#2006] opened 2020-02-03 10:01 UTC
Hello,

I encountered an issue with the following code:
```php
$end = Carbon::create(2020, 2, 29);
$start = Carbon::create(2018, 3, 01);
$diffInMonths = $end->diffInMonths($start);
echo $diffInMonths;
```

Carbon version: **2.29.1**

PHP version: **7.3.12**

I expected to get:

```
23
```

But I actually get:

```
24
```

Thanks!

**Comment by sergiodebcn** [comment] 2020-02-03 10:27
Hi, I think this is related with:
https://bugs.php.net/bug.php?id=76032

**Comment by kylekatarnls** [comment] 2020-02-03 12:33
Sorry but why would it be 24? All diffIn* methods returns an integer result rounded down. So from 2018-03-01 (implicitly midnight) to 2020-03-01 (implicitly midnight) this is exactly 24 months, 1 day less, it's 24 - 1/29 = 23.966 => casted as integer, you get 23 as promised. Leap year is correctly taken into account.

Note: use `Carbon::create(2018, 3, 1)` instead of `Carbon::create(2018, 3, 01)` numbers starting with `0` will be understood as octal, so for example `08` throws an exception in PHP.

**Comment by jcerrada** [comment] 2020-02-03 12:48
But it's not from 2018-03-01 (implicitly midnight) to 2020-03-01, it's from **2018-03-01** to **2020-02-29**.  
Actually, if we do the test for the previous year, it returns 23
```php
$end = Carbon::create(2019, 2, 28);
$start = Carbon::create(2017, 3, 1);
$diffInMonths = $end->diffInMonths($start);
echo $diffInMonths;
```

**Comment by kylekatarnls** [comment] 2020-02-03 12:55
Sorry, I swapped the expected/actual because it get 23 in UTC and America timezone, but indeed using European timezone output 24. So @sergiodebcn is probably right, it could be https://bugs.php.net/bug.php?id=76032 and not a problem Carbon is responsible for. I will try to make a equivalent code using pure PHP.

Please consider using UTC for every calculation server-side. I explained here more in detail why timezones should be reserved for user display/input while the server should only work with UTC: https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164

**Comment by kylekatarnls** [comment] 2020-02-03 13:01
PHP bug confirmed:
```php
date_default_timezone_set('America/Toronto');

var_dump((new DateTime('2018-03-01'))->diff(new DateTime('2020-02-29'))->format('%Y years %M months'));

date_default_timezone_set('UTC');

var_dump((new DateTime('2018-03-01'))->diff(new DateTime('2020-02-29'))->format('%Y years %M months'));

date_default_timezone_set('Europe/Paris');

var_dump((new DateTime('2018-03-01'))->diff(new DateTime('2020-02-29'))->format('%Y years %M months'));
```
Output:
```
string(18) "01 years 11 months"
string(18) "01 years 11 months"
string(18) "02 years 00 months"
```

This issue should be fixed PHP-side.

**Closed by kylekatarnls** 2020-02-03 13:01 UTC
Labels: php bug

**Comment by jcerrada** [comment] 2020-02-03 13:06
Ahh ok ok thanks for taking the time @kylekatarnls @sergiodebcn!
