### ISSUE TITLE
Declaration of Carbon\Translator after Laravel 7 Upgrade

### ISSUE THREAD

**Issue by stevenhardy-digital** [briannesbitt/Carbon#2033] opened 2020-03-07 19:13 UTC
Hello,

I encountered an issue with the following code:
```php
Carbon\Translator::trans($id, array $parameters = Array, $domain = NULL, $locale = NULL)
```

Carbon version: **2.31.0**

PHP version: **7.3.9**

I expected to get:

```
Declaration of Carbon\\Translator::trans($id, array $parameters = Array, $domain = NULL, $locale = NULL) must be compatible with Symfony\\Contracts\\Translation\\TranslatorInterface::trans(string $id, array $parameters = Array, ?string $domain = NULL, ?string $locale = NULL) at /home/vagrant/folder/website/vendor/nesbot/carbon/src/Carbon/Translator.php:18)
```

But I actually get:

```
Laravel website 500 error
```

Thanks!

**Comment by kylekatarnls** [comment] 2020-03-08 09:35
The easy fix is to add the missing typing to be aligned with Symfony 5.

But this will require to drop PHP 7.1, Symfony < 5 (and so Laravel < 7). This means any user having one of those dependencies in a lower version will be stuck with Carbon 2.31.x patches and no new features. This can be painful for the project maintenance and the documentation.

So I have to consider this wisely.

**Comment by kylekatarnls** [comment] 2020-03-08 09:39
I'm really surprise this throws an exception as our unit tests for Translator::trans succeed using PHP 7.3 and Symfony 5.0.5:
https://travis-ci.org/briannesbitt/Carbon/jobs/658182113?utm_medium=notification&utm_source=github_status

**Comment by kylekatarnls** [comment] 2020-03-08 09:40
Could you please try to provide an minimum code chunk to reproduce the Carbon issue outside Laravel?

**Comment by sperelson** [comment] 2020-03-08 16:11
Just seconding the issue. Brand new install on PHP 7.3.12 has the same errors. Installed on PHP 7.4.1 and it runs without errors. Could be a configuration difference. The `Fix` commit linked above is what I did to resolve it temporarily.

**Comment by kylekatarnls** [comment] 2020-03-08 18:07
> Won't fixing the declaration mean forcing the use of "symfony/translation": "^5.0"?

On the contrary, the declaration is currently covariant (it's valid and the unit tests are passing for all versions), if I update the declaration to be exactly the same as the current 5.0 implementation, it will break Symfony < 5.

You always need to be sure that composer run the same PHP version when it installs the dependencies that the one your run for the webserver and Indeed I guess the issue is the same for @stevenhardy-digital.

**Comment by Jaspur** [comment] 2020-03-10 20:59
This occurs also to me. 
I force my PHP-version of the server in my composer file:
```
"config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "platform": {
            "php": "7.2.24"
        },
        "sort-packages": true
    },
```
But still getting those errors.

**Comment by rimace** [comment] 2020-03-11 12:58
Basically it's [line 314 in Translator.php](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Translator.php#L314).
That needs to be `public function setLocale(string $locale)` (notice the type-hint) and the errors would be fixed in my opinion, right?

**Comment by kylekatarnls** [comment] 2020-03-11 13:05
As you can see there: https://travis-ci.org/github/kylekatarnls/Carbon/builds/659770462

Aligning the typehint will break Symfony < 5 compatibility and PHP < 7.2 compatibility and as you can see here: https://travis-ci.org/github/kylekatarnls/Carbon/builds/659768977

The library on its own with the current typing is compatible with all versions of PHP and Symfony.

So I won't break anything without until I have the exact cause of the error (a way to reproduce the error.

Mabe FastCGI may behave differently regarding typing covariance. Can you compare with standard PHP cli if the same app runs please?

**Comment by tai1030** [comment] 2020-03-13 14:44
Hi all,
I have same issues too.

PHP version: **7.4.0**
Carbon version: **2.31.0**
Laravel version: **7.1.1**
Symfony/translation version: **5.0.5**

Error: Laravel 500 with below error log:
> Declaration of Carbon\Translator::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale)

But my environment is a bit special, I am not running Laravel on Apache / FastCGI / PHP-FPM, etc.
I am running Laravel on CLI with "[LaravelS](https://github.com/hhxsv5/laravel-s)" package. I am not sure is it related.

However, my workaround is forked this repository, add typehint to both Translator::trans() and Translator::setLocale() by follow Symfony 5, and use composer VCS to require my own Carbon package to my project, now everything is good for my own project. I know that is a bad idea, but I can't do anything if I don't do that. If anyone facing same issue, can consider to use this workaround too.
https://github.com/tai1030/Carbon/commits/2.31.0-patch2

**Comment by kylekatarnls** [comment] 2020-03-13 19:04
As proven by Travis-CI (and many successful Laravel 7 deployments), Carbon implement **is compatible** with PHP 7.0 to 7.4 and Symfony 3.4 to 5 :

See this code: https://3v4l.org/c7ppR

Please try this simple chunk on your own environment. If your PHP program works as expected (respect the PHP documentation and source code) it should not throw any declaration compatibility error.

I (and most libraries) use PHP standard CLI to test their library and consider than if a bug occurs in some environment but not in the CI platform (Travis-CI for Carbon) then it's an environment issue.

As soon as someone could provide a way to reproduce the bug (using a particular settings, PHP implementation, dependency list) then I would be able to add the bug to our tests and fix it without breaking their app to other users.

**Comment by kylekatarnls** [comment] 2020-03-13 20:37
For the record, this message "Declaration of ... must be compatible" is the one you were supposed to see before covariance was introduced (PHP < 7.2), but with PHP < 7.2, composer install Symfony 3 or 4 but not 5 which requires PHP >= 7.2.

So if you have this error, you should double-check you are really running the composer installation and the environment that throws the exception with the same PHP version.

**Comment by kylekatarnls** [comment] 2020-03-16 10:42
Regarding the lack of elements that would allow to reproduce the bug in a CLI environment or could confirm it really happen with PHP >= 7.2, I close this issue.

Please refer https://github.com/briannesbitt/Carbon/issues/2033#issuecomment-596185060

If you get this error message, there are great chances you're not running the PHP version you think, you're more likely running a PHP version lower than 7.2, and so that is actually not compatible with Laravel 7 / Symfony 5.

**Closed by kylekatarnls** 2020-03-16 10:42 UTC
Labels: wrong version used

**Comment by kylekatarnls** [comment] 2020-07-20 14:51
The possible causes and solutions have been given yet: https://github.com/briannesbitt/Carbon/issues/2033#issuecomment-596185060

**Comment by zachweix** [comment] 2020-07-20 15:20
Yeah, I realized afterwards. Once I fixed everything so that it was actually running on PHP 7.4 all was good again
