### ISSUE TITLE
Issue with daylight saving timezones

### ISSUE THREAD

**Issue by umairrafiq1133** [briannesbitt/Carbon#2569] opened 2022-03-15 11:35 UTC
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromFormat('Y-m-d H:i', '2022-03-15 10:00', 'America/Los_Angeles')->setTimezone('UTC');
echo Carbon::createFromFormat('Y-m-d H:i', '2022-03-15 10:00', 'PDT')->setTimezone('UTC');
```

Carbon version: **2.31**

PHP version: **7.4.9**

I expected to get:

```
2022-03-15 17:00:00
2022-03-15 17:00:00
```

But I actually get:

```
2022-03-15 17:00:00
2022-03-15 18:00:00
```

With daylight savings in affect, America/Los_Angeles and PDT both should be at GMT-7 but its not the case.
When I run first line, I get 2022-03-15 17:00:00 but for second line my output is 2022-03-15 18:00:00 which should have been 2022-03-15 17:00:00 because both timezones are identical.

Thanks!

**Comment by umairrafiq1133** [comment] 2022-03-15 11:41
![image](https://user-images.githubusercontent.com/18613802/158370402-a3d59b60-7b3e-4d07-9449-76b648e456a1.png)
![image](https://user-images.githubusercontent.com/18613802/158370552-43891735-8cb4-490f-9180-ec0e1386362c.png)

**Comment by umairrafiq1133** [comment] 2022-03-15 12:16
echo Carbon::now('PDT');
echo "<br>";
echo Carbon::now('America/Los_Angeles');

2022-03-15 04:15:01
2022-03-15 05:15:01

**Comment by kylekatarnls** [comment] 2022-03-16 10:23
Indeed it sounds like a bug as PDT should match Los Angeles timezone on 2022-03-15

But here Carbon just reflect the PHP behavior:
https://3v4l.org/uu12B

And it sounds to be the same in all PHP versions since 5.5.10.

So it's very likely a bug (a regression as behavior was different in <= 5.5.9) in PHP (to be searched in https://bugs.php.net/)

**Comment by kylekatarnls** [comment] 2022-03-16 10:32
I opened it: https://github.com/php/php-src/issues/8205 waiting for their triage or explanation. But I'm closing this issue as we can't actually do anything about it unless maintaining our own database of timezones and DST changes (we won't).

**Closed by kylekatarnls** 2022-03-16 10:32 UTC
Labels: php bug

**Comment by damianwadley** [comment] 2022-03-16 11:10
"PDT" is a convenient acronym for people but not a reliable timezone identifier. You should be using names like `America/Los_Angeles` (which observes DST changes) or offsets like `-0700` (which does not).

**Comment by umairrafiq1133** [comment] 2023-05-16 13:03
$date = Carbon::now('America/Detroit');
echo $date->timezone->getAbbreviatedName();

This is resulting in `CST` but when I see compare CST and America/Detroit time, there is an hour difference.

**Comment by damianwadley** [comment] 2023-05-16 13:36
@umairrafiq1133 That would be because America/Detroit is currently observing DST, but when  you called getAbbreviatedName you didn't pass $dst=true.
https://carbon.nesbot.com/docs/
