### ISSUE TITLE
symfony/translation:^6.0

### ISSUE THREAD

**Issue by XNicON** [briannesbitt/Carbon#2508] opened 2021-11-30 20:18 UTC
Hello,

problem install full pack symfony 6.0

please add composer require
symfony/translation:^6.0 

Thanks!

**Comment by kylekatarnls** [comment] 2021-11-30 20:39
Hello, 👋 

It's not that simple as `Carbon\Translator::trans($id, array $parameters = [], $domain = null, $locale = null)` must be compatible with `Symfony\Component\Translation\Translator::trans(?string $id, array $parameters = [], ?string $domain = null, ?string $locale = null): string` so have to choose between Symfony < 6 and Symfony >= 6, and dropping support for Symfony 5 and below would be a breaking change.

So it needs a rework or else it will be possible only in Carbon 4.

Pull request to allow Symfony 6 compatibility without breaking currently supported version is very welcome.

**Comment by nforced** [comment] 2021-12-01 08:34
Is is possible to use Carbon without translations? I don't really need them. Now it's the case where I use the lib but can't upgrade to 6.0 because of this and looking for a way to overcome this in a quick way :smiley:

**Comment by Chris53897** [comment] 2021-12-01 12:03
First idea i created in my lunch break.
Normally i use the check with Kernel::VERSION_ID but we need here a smarter way to check the version.
Maybe with reflection? Checks do not pass yet.
https://github.com/Chris53897/Carbon/commit/dbe0f061a65d9b763111e52bdde939e273d48380

**Comment by kylekatarnls** [comment] 2021-12-01 13:37
It's the good track. The issue with `Kernel` is that it's in the complete Symfony framework but not in the translation sub-package (the only one Carbon depends on). We'll want to be able to detect symfony/translation is a v6 or lower even if the app where it's installed does not use the full framework. So yes, probably reflection and type checking.

**Comment by kylekatarnls** [comment] 2021-12-01 14:34
Basic typing compatibility is now fixed. But we'll have a big refactor ahead to be compatible with Symfony 6 as we have translations like this:
```php
    'from_now' => function ($time) {
        return (preg_match('/^[0-9].+$/', $time) ? 'tra' : 'in')." $time";
    }
```
to handle particular grammar rules, but Symfony now longer allow this in the `MessageCatalogue::get()` function which now strictly requires the return type to be a `string`.

**Comment by nforced** [comment] 2021-12-01 14:45
A quick look doesn't show any significant difference in 5.4 and 6.1 trans()

[5.4](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Translation/Translator.php#L197)
`public function trans(?string $id, array $parameters = [], string $domain = null, string $locale = null)`

[6.1](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Translation/Translator.php#L176)
`public function trans(?string $id, array $parameters = [], string $domain = null, string $locale = null): string`

[Carbon](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Translator.php#L150)
`public function trans($id, array $parameters = [], $domain = null, $locale = null)`

What is the actual problem with `"symfony/http-kernel": "^3.4 || ^4.0 || ^5.0 || ^6.0"`?

**Comment by Chris53897** [comment] 2021-12-01 14:46
I see you allready fixed the first problems in your [branch](https://github.com/briannesbitt/Carbon/commits/feature/symfony6). Great. https://github.com/symfony/translation/blob/6.0/MessageCatalogue.php#L126

I just added some links, so we can follow your thoughts ;)

**Comment by Chris53897** [comment] 2021-12-01 14:49
The symfony/http-kernel is just an idea. The problem is that these versions are probably not the same. We need the version of symfony/translation. But how do we get it? I know the command to get it from composer, but that does not help much here.

**Comment by nforced** [comment] 2021-12-01 14:53
> The symfony/http-kernel is just an idea. The problem is that these versions are probably not the same. We need the version of symfony/translation. But how do we get it? I know the command to get it from composer, but that does not help much here.

How about this? [https://getcomposer.org/doc/07-runtime.md](https://getcomposer.org/doc/07-runtime.md)

**Comment by Chris53897** [comment] 2021-12-01 15:01
Good idea. Quicktest works. But i am not sure what thinks we have to consider with this solution. 
\Composer\InstalledVersions::getVersion('symfony/translation')
string(7) "6.0.0.0"

**Comment by kylekatarnls** [comment] 2021-12-01 15:30
symfony/http-kernel is not an option: we should not embed a package made for HTTP Kernel just to guess the version of a package

`\Composer\InstalledVersions`  is not great neither as it drops Composer 1 compatiblity.

I still think the Reflection https://github.com/briannesbitt/Carbon/commit/105b30fc729ec4d9a3d9f51760de2e96b6c0dddd#diff-e10ba6a836bd0ec56e856e73ba2145575d9561b3ac40f734b6dc4bca918440d2R17 is a good option because knowing if we have a return type on the method is exactly what we want to know and the reason why we need to use strong type or weak type.

**Comment by kylekatarnls** [comment] 2021-12-01 15:52
> A quick look doesn't show any significant difference in 5.4 and 6.1 trans()

We don't only use `trans()` we use many other methods of the symfony/translation package such as `MessageCatalogue::get()` as explained [here](https://github.com/briannesbitt/Carbon/issues/2508#issuecomment-983701240)

It's sure easy to fix for each specific application stack, but what we need is a common solution working for all at the same time (because we don't want to break the internet), so keeping 2.x compatible with the current set of supported PHP/composer/Symfony/etc. versions.

So you can help if you want using a draft pull-request for instance, so you'll see via GitHub Actions build status if it's still compatible with lower version of Symfony (>=3.4), PHP (>=7.1.8) and if new dependencies are involved in the change, they will be weighted carefully because they also can make installation impossible (if a package conflicts with it or depends on incompatible versions), that's why I would prefer solution that does not require more packages.

I'll come back later to this, but feel free to fork [feature/symfony6 branch](https://github.com/briannesbitt/Carbon/tree/feature/symfony6) if you have time sooner to propose a solution.

**Comment by nforced** [comment] 2021-12-01 16:45
> I'll come back later to this, but feel free to fork [feature/symfony6 branch](https://github.com/briannesbitt/Carbon/tree/feature/symfony6) if you have time sooner to propose a solution.

At first, it is absolutely mandatory to have translations? Isn't default/fallback datetime format or even config/packages/.yaml file where this can be configured something that can make the translations optional? For example I mostly use `Carbon::now('UTC')->toDateTime();` to store microtime in db and personally don't need dates like '19ти Декември 2021'.

**Comment by kylekatarnls** [comment] 2021-12-01 17:01
I'm not rejecting the idea, but refactoring the lib to make translations optional will clearly be even longer than supporting Symfony 6 and probably not possible without breaking changes.

**Comment by Chris53897** [comment] 2021-12-01 17:04
In my opionen this should be discussed in an an seperate issue. So we can focus on symfony 6 in this Issue.

**Closed** 2021-12-02 17:13 UTC

**Comment by kylekatarnls** [comment] 2021-12-02 17:26
Version 2.55.0 released with Symfony 6 support. It will probably move a little to make a better use of the new symfony/translation features. And I did not deep tested if everything in every languages behave exactly the same with Symfony 6 so your feedback is welcome if something broke but at least now installation is not blocked.

**Comment by Chris53897** [comment] 2021-12-02 17:54
This was the last piece to upgrade my bundle to Symfony 6. Thank you

**Comment by XNicON** [comment] 2021-12-03 08:05
last 2.54.0 on https://packagist.org/packages/nesbot/carbon

**Comment by kylekatarnls** [comment] 2021-12-03 09:10
Updated

**Comment by mikerockett** [comment] 2021-12-03 10:00
Composer is throwing PSR issues now:

```
Class Carbon\Translator located in ./vendor/nesbot/carbon/src/Carbon/TranslatorWeakType.php does not comply with psr-4 autoloading standard. Skipping.
Class Carbon\Translator located in ./vendor/nesbot/carbon/src/Carbon/TranslatorStrongType.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by kylekatarnls** [comment] 2021-12-03 12:40
Yes, basically we should just put those files outside the `src` folder so composer won't try to load them.

As said above, 2.55.0 was a way to quickly unlock installation with Symfony 6, this will still move and properly fixed with no rush.
