### ISSUE TITLE
str_starts_with() 

### ISSUE THREAD

**Issue by aryala7** [briannesbitt/Carbon#2399] opened 2021-07-28 11:16 UTC
Hello,
i encountered an issue after updating to the latest version

Carbon version: **2.51.0**

PHP version: **7.4**

![carbon_bug](https://user-images.githubusercontent.com/56627259/127313640-ab796b48-3475-4378-b2dc-5a37f7df4ec2.png)Thanks!

**Comment by kylekatarnls** [comment] 2021-07-28 12:08
Hello :wave

I need the complete stack trace to solve this and the code you run that called it. Thanks.

**Comment by drewwynne0** [comment] 2021-07-28 17:36
str_starts_with is a PHP8 only function.  With this release, Carbon has effectively just dropped support for PHP7.x

https://www.php.net/manual/en/function.str-starts-with.php

**Comment by kylekatarnls** [comment] 2021-07-28 19:57
😄 Hopefully not [symfony/polyfill-php80](https://packagist.org/packages/symfony/polyfill-php80)

**Comment by trevorgehman** [comment] 2021-07-28 19:57
@drewwynne0 This package uses the php8 polyfill by Symfony, so it will work fine on PHP 7. However, I just ran into this issue as well after updating my dependencies:

<img width="885" alt="CleanShot 2021-07-28 at 14 52 15@2x" src="https://user-images.githubusercontent.com/3209864/127387007-32fb178f-f2ea-4669-820d-cf76e6a1610c.png">

I believe the cause is this pull request: https://github.com/briannesbitt/Carbon/pull/2393

The issue is that `substr()` accepts `null` but `str_starts_with()` does not.

**Comment by kylekatarnls** [comment] 2021-07-28 20:04
Thanks @trevorgehman stack strace is a good start but I still miss the code called to reproduce the error, here you mention: a usage that could for instance be called with `Carbon::createFromTimestampMsUTC(null)` but it's not a valid usage as this methods expect `@param float|int|string $timestamp` (does not allow `null`) I will fix it if it's a regression for a valid case: a usage where having `null` is relevant, if not then it will be better to keep it strict and fix your code to not pass `null` in the method rather than allowing it because converting silently `null` to something else (such as `0` for `createFromTimestampMsUTC` will lead to unexpected and hard to debug behavior, so you better have a fatal error here IMO).

I can give more accurate feedback and determine if it needs to be fixed or not only if you can provide legit example of usage where `null` get passed in.

**Comment by drewwynne0** [comment] 2021-07-28 20:11
@kylekatarnls @trevorgehman fair point, though still somewhat of a frustrating change for a minor release.

**Comment by trevorgehman** [comment] 2021-07-28 20:12
I agree @kylekatarnls I prefer it throwing a type error actually. This change helped me uncover an issue where I was passing `null` into `Carbon::createFromTimestampUTC()` in some situations inadvertently.

Previously passing `null` or a random string to this method would return:

```
=> Carbon\Carbon @0 {#3011
     date: 1970-01-01 00:00:00.0 +00:00,
   }
```

But now passing `null` will throw a type error. Passing a random string still returns the same thing FYI.

**Comment by kylekatarnls** [comment] 2021-07-28 20:29
> though still somewhat of a frustrating change for a minor release

Why? Please concrete reason if you still think so.

@trevorgehman that's exactly the point, we will have this error anyway with PHP 8 because type become stricter (and it will be even a bit more with PHP 8.1). I don't want to push hard in this direction, but step by step we'll try to follow this best-practices move, in this precise case `timestamp = 0` is fairly 1970-01-01 but `timestamp = null` is 99% of the case not meant to represent 1970-01-01, so we're on the safe side having an error making it more obvious for the developer that she/he should not create a date with this and handle it in its own code before to have a output that will be relevant with her/his own business logic.

@aryala7 I wait for your feedback, if you have an other case you think is valid use case for supporting `null` I will handle it, else I will assume it's the same use case and close it.

**Comment by trevorgehman** [comment] 2021-07-28 20:34
@kylekatarnls Makes complete sense. These kinds of things are inevitable with the direction PHP is moving, as you said. It's a good thing ultimately.

**Comment by drewwynne0** [comment] 2021-07-28 21:04
> > though still somewhat of a frustrating change for a minor release
> 
> Why? Please provide concrete reason if you still think so.

First of all I would like to add that I agree that moving to the PHP8 alternatives is the correct approach and thank you for your efforts in updating the project to do this.  I would also agree that it is correct for developers to address their code accordingly.

However, I would argue that if you are making potentially breaking changes because the function you are moving to has stricter criteria on what it will accept, then either these changes should be kept for a major version, or the changes should account for currently accepted arguments in the current major version, removing support thereafter.  

This allows developers to address severe issues in development and not worry about a minor increment causing a potential issue in production when traffic increases and your load balancer spins up new nodes.

I would also argue that this is the primary purpose behind major/minor version separation.

**Comment by kylekatarnls** [comment] 2021-07-28 21:30
> then either these changes should be kept for a major version

First, every change is a breaking change. If I create a new method `stupidThing()` but you extend the `Carbon` class and you already used this name, you get a conflict error or worse, so adding anything can potentially breaks a developer workflow, and when there is so many user-specific use cases like for Carbon, you hit a BC for someone quite easily even with an innocent patch for a very edge-case.

That's why semantic version (by the way, one library is not forced to follow this convention) is a matter of considering what usage is legit so you can determine what is actually a BC for your own policy. I detailed years ago what is our policy regarding this for Carbon:
https://github.com/briannesbitt/Carbon/blob/master/contributing.md#versioning

which is a compromise so the library does not bump to next major every month (else developers, and frameworks like Laravel would probably not follow the upgrades) and still be able to evolve in a rational way.

The precise application of this policy for typing is the following:
- when there is a PHP type hint, it has precedence
- else, if there is unit test covering a use case, it's a valid use case we'll do our best to continue to support
- else, PHPDoc substitues PHP type hint, for instance `createFromTimestampMsUTC()` accepts `float|int|string` according to PHPDoc, this will become `createFromTimestampMsUTC(float|int|string $timestamp)` in PHP 8 (Carbon 3). But as long as we support PHP 7, we can't use union type, so we use PHPDoc instead, but it does not mean we're more tolerant: we don't support there `null`, else we would have document it as `float|int|string|null` (this PHPDoc is reflected in https://carbon.nesbot.com/docs/ reference page) and should be shown in smart IDEs. We won't validate every input for every unexpected types that may happen in every function, it would bloat a lot the library, we rely on developers following the PHPDoc and avoid any ambiguous situation which is not only a higher risk to experience BC, but most importantly a source of trouble for you and your team: imagine a developer in front of `Carbon::createFromTimestampMsUTC($value)` wondering what happen if `$value = null`, this dev will have to try because there is no relevant result for such input and will wonder if 1970-01-01 is really what the one who wrote that meant, maybe this person is no longer in the team, maybe it's you and you don't remember 🤷 so I hope such errors will be helpful and probably worth not to wait for 3.x.

And as said, I never meant to allow `null` in `createFromTimestampMsUTC()` it only worked because `strpos()` fails silently before PHP 8.

**Comment by drewwynne0** [comment] 2021-07-28 21:53
Fair points. Rock and a hard place sometimes, but in fairness you've issued fair warning to repo users. 

Thank you for your detailed responses!

**Comment by aryala7** [comment] 2021-07-29 09:19
Thanks for your response @kylekatarnls.  you are completely right I’ve changed my use case and everything works well again.

**Comment by kylekatarnls** [comment] 2021-07-29 10:13
Thanks everybody, glad to hear the alternative is fine for you all.

**Closed by kylekatarnls** 2021-07-29 10:13 UTC
