### ISSUE TITLE
Carbon dealing with Daylight Saving Time(DST)

### ISSUE THREAD

**Issue by Shagun-29** [briannesbitt/Carbon#2305] opened 2021-03-17 23:04 UTC
Hello,
I encountered that Carbon does not deal with DST. For example :- Daylight Saving Time (DST) in Canada starts on the 2nd Sunday in March and ends on the 1st Sunday in November.
I encountered an issue with the following code. As Canada time changes to India time it shows difference as the difference after 1st Sunday in November.
```php
$newDate = Carbon::createFromFormat('Y-m-d H:i:s', '2021-03-17 19:30:00', 'EST');
$newDate->tz = 'Asia/Kolkata';
```

Carbon version: **PUT HERE YOUR CARBON VERSION (exact version, not the range)**

PHP version: **PUT HERE YOUR PHP VERSION**

I expected to get:

```
Canada -> 2021-03-17 19:30:00
India -> 2021-03-18 05:00:00
```

But I actually get:

```
Canada -> 2021-03-17 19:30:00
India -> 2021-03-18 06:00:00
```

Thanks!

**Comment by kylekatarnls** [comment] 2021-03-18 10:25
Hello, Kolkata should have +5:30 while EST is -5 so I don't get why your expecting 19:30 and 4:30.

Then the code use a string not compatible with the format.

Can you please double-check your issue data and fulfill the versions too.

Then ideally provide a code chunk I can use on:
https://try-carbon.herokuapp.com

which would give to me the same result you get so I can reproduce then inspect it.

**Comment by Shagun-29** [comment] 2021-03-18 17:57
Thanks Kyle for your response.

I have cross checked all the formats, nothing is wrong with format or versions.
Actually after March 14 (Sunday) timezone changed to DST that's why it shows difference of 1 hours. I have attach snippet regarding same where Canada time is 01:30 pm and it is expected to get 11:00pm (Kolkata) it results 12:00am (Kolkata).

`DST is the practice of resetting clocks ahead by an hour in spring, and behind by an hour in autumn (or fall). Clocks in the US will “fall back” an hour on Sunday, signalling the end of Daylight Saving Time (DST) this year. In Europe, the same happened on October 25`

Converting time to other timezone i.e EST to Asia/Kolkata, EST to PDT
Canada Time (EST) -> 2021-03-18 13:30 -> 18 March 2021, 01:30pm
India Time (Asia/Kolkata) -> 2021-03-18 -> 18 March 2021, 11:30pm **(Incorrect)**
California Time (PDT) -> 2021-03-18 -> 18 March 2021, 10:30 am **(correct)**

Snippet
            

> Log::info("------------------------------------------------------------");
>             $carbon = Carbon::createFromFormat('Y-m-d H:i:s', '2021-03-18 13:30:00', 'EST');
>             Log::info('Canada Time = '.$carbon);
>             $carbon->tz = 'Asia/Kolkata';
>             Log::info('India (Kolkata) Time = '.$carbon);
>             Log::info("------------------------------------------------------------");
>             $carbon2 = Carbon::createFromFormat('Y-m-d H:i:s', '2021-03-18 13:30:00', 'EST');
>             Log::info('Canada Time = '.$carbon2);
>             $carbon2->tz = 'PDT';
>             Log::info('California (PDT) Time = '.$carbon2);
>             Log::info("------------------------------------------------------------");

  
![Screenshot 2021-03-18 at 1 49 45 PM](https://user-images.githubusercontent.com/35799761/111672975-e04d5f80-87f0-11eb-8eeb-9622ce9d9eee.png)

This is an issue of getting difference of 1 hour may be because of DST timezone.

**Comment by kylekatarnls** [comment] 2021-03-18 18:26
I'm perfectly aware of what is DST. Missunderstanding on how timezones and DST are handled by PHP is the topic for half the issues opened here each year in March and October.

But in your original post, there is `H:i`, here in your snippet you have `H:i:s` and you also say you expect to get `04:30` while it's `19:30` in EST those I absolutely don't understand why you would expect that.

Please edit your original message, pick PHP and Carbon versions you're using, fix the code so it can be ran in https://try-carbon.herokuapp.com and match actual output (or precise both if you get a different one in your environment), then fix the expected output, so we be aligned.

Also what is the result when running pure PHP instead of Carbon:
```php
$newDate = DateTime::createFromFormat('Y-m-d H:i', '2021-03-17 19:30:00', new DateTimeZone('EST'));
$newDate->setTimezone(new DateTimeZone('Asia/Kolkata'));

echo $newDate->format('Y-m-d H:i:s');
```

If you get the same output as with Carbon, the bug is likely not in Carbon but in PHP itself, or there is a misunderstanding on what your be the correct behavior. That's why I would like to first have a consistent and complete description in the initial post before going further.

Thanks.

**Comment by Shagun-29** [comment] 2021-03-18 18:35
Thanks @kylekatarnls for letting me know and I apologise for that inconvenience, that was typo.
I have correct the initial message.

**Comment by kylekatarnls** [comment] 2021-03-18 19:23
It sounds like EST/EDT is broken in PHP:
```php
$d = DateTime::createFromFormat('Y-m-d H:i', '2021-03-17 19:30', new DateTimeZone('EST'));
$d->setTimezone(new DateTimeZone('Asia/Kolkata'));

echo $d->format('Y-m-d H:i:s') . "\n";

$d = DateTime::createFromFormat('Y-m-d H:i', '2021-03-17 19:30', new DateTimeZone('EDT'));
$d->setTimezone(new DateTimeZone('Asia/Kolkata'));

echo $d->format('Y-m-d H:i:s') . "\n";

$d = DateTime::createFromFormat('Y-m-d H:i', '2021-03-17 19:30', new DateTimeZone('America/Toronto'));
$d->setTimezone(new DateTimeZone('Asia/Kolkata'));

echo $d->format('Y-m-d H:i:s') . "\n";

$d = DateTime::createFromFormat('Y-m-d H:i', '2021-03-13 19:30', new DateTimeZone('EST'));
$d->setTimezone(new DateTimeZone('Asia/Kolkata'));

echo $d->format('Y-m-d H:i:s') . "\n";

$d = DateTime::createFromFormat('Y-m-d H:i', '2021-03-13 19:30', new DateTimeZone('EDT'));
$d->setTimezone(new DateTimeZone('Asia/Kolkata'));

echo $d->format('Y-m-d H:i:s') . "\n";

$d = DateTime::createFromFormat('Y-m-d H:i', '2021-03-13 19:30', new DateTimeZone('America/Toronto'));
$d->setTimezone(new DateTimeZone('Asia/Kolkata'));

echo $d->format('Y-m-d H:i:s') . "\n";
```
https://3v4l.org/JAeR2

You can see in this example (where Carbon is not involved at all) that only `America/Toronto` gives a correct output.

PHP has plenty of known timezone bugs, I will check if this is one of them.

To be safe, I recommend using America/Toronto if this is actually a human input from someone in Canada, or UTC for anything else.

**Comment by kylekatarnls** [comment] 2021-03-18 19:25
I found this work-around:
```php
$newDate = Carbon::createFromFormat('Y-m-d H:i:s e', '2021-03-17 19:30:00 EST');
$newDate->tz = 'Asia/Kolkata';
```

**Comment by kylekatarnls** [comment] 2021-03-18 19:28
For the reference the bug is known and open PHP-side since 2017 😢 
https://bugs.php.net/bug.php?id=74671

So I will close this issue and hope you can work with the work-around above.

**Closed by kylekatarnls** 2021-03-18 19:28 UTC
Labels: php bug

**Comment by Shagun-29** [comment] 2021-03-21 21:39
Thanks @kylekatarnls 😅  it was helpful 👍
