### ISSUE TITLE
Carbon 2 is not updating

### ISSUE THREAD

**Issue by Sam-Black-0013** [briannesbitt/Carbon#1781] opened 2019-07-09 07:30 UTC
Hello,

I encountered an issue when updating Carbon 1 => 2.
I am using Craft CMS 3, and when I update the composer, a deprecation errors states that i should update Carbon 1 to Carbon 2.

This is the message:

> Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run ".\vendor\bin\upgrade-carbon" to get help in updating carbon and other frameworks and libraries that depend on it.

I tried to run the command, got a message to confirm the update, confirmed it, but composer tells me that nothing to install or update. Is there anyway I can update it ?

Carbon version: 1.39.0

PHP version: 7.1.10

Thanks!

**Comment by kylekatarnls** [comment] 2019-07-09 08:01
It probably means that an other dependency is locking Carbon to ^1. Please dump your composer.json require and require-dev sections. If it changes before/after the command, please show both. And dump the composer output.

Thanks.

**Comment by bhargav960143** [comment] 2019-07-09 08:17
@kylekatarnls 

Please find my composer.json file.

```
{
    "name": "envaysoft/fleetcart",
    "description": "The FleetCart E-Commerce System.",
    "type": "project",
    "authors": [
        {
            "name": "Martin Smith",
            "email": "martin@mailinator.com"
        }
    ],
    "require": {
        "php": ">=7.1.3",
        "fideloper/proxy": "^4.0",
        "floatingpoint/stylist": "^0.5",
        "fzaninotto/faker": "~1.4",
        "jackiedo/dotenv-editor": "^1.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "nwidart/laravel-modules": "^3.0",
        "spatie/laravel-activitylog": "^3.2",
        "swayok/alternative-laravel-cache": "^5.4",
        "symfony/intl": "^4.1",
        "wikimedia/composer-merge-plugin": "^1.4",
        "nesbot/carbon": "^1.26.3"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.0",
        "beyondcode/laravel-dump-server": "^1.0",
        "beyondcode/laravel-query-detector": "^1.0",
        "composer/composer": "^1.8",
        "filp/whoops": "^2.0",
        "nunomaduro/collision": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "FleetCart\\": "app/",
            "Modules\\": "Modules/",
            "Themes\\": "Themes/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate"
        ]
    },
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true,
        "preferred-install": "dist",
        "platform": {
            "php": "7.1.3"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
                "nwidart/laravel-modules"
            ]
        },
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        },
        "merge-plugin": {
            "require": [
                "Modules/*/composer.json",
                "Themes/*/composer.json"
            ],
            "merge-extra": true,
            "merge-extra-deep": true,
            "merge-scripts": true
        }
    }
}

```

**Comment by kylekatarnls** [comment] 2019-07-09 08:53
Hi, it seems you remove your message. But if the composer.json that was previously here was right, you're locked by nwidart/laravel-modules in Laravel 5.6. Both Laravel 5.6 and Carbon 1 are no longer actively supported. Upgrade nwidart/laravel-modules to allow updates of the other packages. I did not check all the sub-dependencies. So you may possibly have other lockers you need to track.

**Comment by kylekatarnls** [comment] 2019-07-09 12:03
I tried a simple install with just the last version of Craft CMS 3 and Carbon 1.39, then ran the upgrade-script. It worked fine. So there is no restriction in Craft CMS 3 itself, I need more details to reproduce your issue.

**Comment by kylekatarnls** [comment] 2019-07-13 09:32
I assume you found the package requiring Carbon < 2 in your dependencies. So I close the issue. If you still have the issue, please provide requested details above and I will re-open.

**Closed by kylekatarnls** 2019-07-13 09:32 UTC
Labels: details needed

**Comment by akanshutambi811** [comment] 2019-11-06 11:20
Hello,

I encountered an issue when updating Carbon 1 => 2.
I am using Craft CMS 3, and when I update the composer, a deprecation errors states that i should update Carbon 1 to Carbon 2.

This is the message:

    Carbon 1 is deprecated, see how to migrate to Carbon 2.
    https://carbon.nesbot.com/docs/#api-carbon-2
    You can run ".\vendor\bin\upgrade-carbon" to get help in updating carbon and other frameworks and libraries that depend on it.

I tried to run the command, got a message to confirm the update, confirmed it, but composer tells me that nothing to install or update. Is there anyway I can update it ?

Carbon version: 1.39.0

**Comment by akanshutambi811** [comment] 2019-11-06 11:20
{
  "require": {
    "craftcms/cms": "3.0.41.1",
    "craftcms/redactor": "2.1.7",
    "dolphiq/craft3-forms": "1.1.0",
    "ether/seo": "3.4.4",
    "ether/simplemap": "3.3.5",
    "solspace/craft-freeform": "2.5.26",
    "spicyweb/craft-neo": "2.1.8",
    "studioespresso/craft-easyaddressfield": "1.4.0",
    "twig/twig": "2.6.*",
    "verbb/cp-nav": "2.0.9",
    "verbb/navigation": "1.1.8",
    "vlucas/phpdotenv": "^2.4.0",
	"cebe/markdown": "~1.1.0",
    "xpertbot/craft-wheelform": "2.2.4"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  },
  

  "minimum-stability": "dev",
  "prefer-stable": true
 

  
}

**Comment by akanshutambi811** [comment] 2019-11-06 11:21
Above file is my composer.jso

**Comment by kylekatarnls** [comment] 2019-11-07 21:56
Please run the command `composer why nesbot/carbon` to see what packages are requiring Carbon 1.x, one of them probably does not accept Carbon 2.

If so, you can either falsify the version number using composer alias (see the main page of the doc https://carbon.nesbot.com/). It's not ideal, because it disallow you to install new packages that require Carbon 2 but do not support Carbon 1.

Or the better solution: contact owners of the packages that "lock" Carbon to its old version to ask them to support the new major version in their compatibility range.
