### ISSUE TITLE
Exception: Unknown getter 'locale'

### ISSUE THREAD

**Issue by FabrizioCafolla** [briannesbitt/Carbon#2217] opened 2020-10-09 09:44 UTC
Hello,

I encountered an issue with the following code:
```      
$holidays = ['0' => '2020-12-25', '1' => '2020-12-24']; //etc..
            
return $start_date->diffInDaysFiltered(function (Carbon $d) use ($holidays) {
   return $d->isWeekday() && !array_search($d->format("Y-m-d"), $holidays,true);
}, $end_date);
```

Carbon version: **2.41.0**

PHP version: **7.3.5**

I expected to get:

```
number of diff days between start_date and end_date
```

But I actually get:

```
Exception: Unknown getter 'locale'
```

**With version 2.40.1 work!**

**Comment by kylekatarnls** [comment] 2020-10-09 23:16
I created `$start_date` and `$end_date` as you did not provide data for those variables and get no issue with some random December dates:

```php
$holidays = ['0' => '2020-12-25', '1' => '2020-12-24']; //etc..

$start_date = Carbon::parse('2020-12-20');
$end_date = Carbon::parse('2020-12-29');

echo $start_date->diffInDaysFiltered(function (Carbon $d) use ($holidays) {
   return $d->isWeekday() && !array_search($d->format("Y-m-d"), $holidays, true);
}, $end_date);
```
You can test it yourself in the sandbox:
https://try-carbon.herokuapp.com/?input=%24holidays%20%3D%20%5B%270%27%20%3D%3E%20%272020-12-25%27%2C%20%271%27%20%3D%3E%20%272020-12-24%27%5D%3B%0D%0A%0D%0A%24start_date%20%3D%20Carbon%3A%3Aparse(%272020-12-20%27)%3B%0D%0A%24end_date%20%3D%20Carbon%3A%3Aparse(%272020-12-29%27)%3B%0D%0A%0D%0Aecho%20%24start_date-%3EdiffInDaysFiltered(function%20(Carbon%20%24d)%20use%20(%24holidays)%20%7B%0D%0A%20%20%20return%20%24d-%3EisWeekday()%20%26%26%20!array_search(%24d-%3Eformat(%22Y-m-d%22)%2C%20%24holidays%2C%20true)%3B%0D%0A%7D%2C%20%24end_date)%3B%0D%0A

2.40.1 and 2.41.0 are available in the sand box and both work fine. Can you produce a code chunk I can reproduce in the sandbox/a local machine.

Side note: You should consider https://github.com/kylekatarnls/business-day to handle holidays.

**Comment by kylekatarnls** [comment] 2020-10-14 11:21
I close this issue as I'm not able to reproduce it. I'll re-open it if you can provide a stand-alone code to trigger the issue.

**Comment by makurtu** [comment] 2021-02-02 11:24
I can confirm this issue in Carbon > 2.40.1.

This issue is in this line: https://github.com/briannesbitt/Carbon/blob/0d87f3d34cd9464e6807df1e41aa5a8ce87adee3/src/Carbon/CarbonPeriod.php#L712
and is caused by this line: https://github.com/briannesbitt/Carbon/blob/a417de2608d14c0598991d1267396d2fd4b7c183/src/Carbon/Traits/Options.php#L411

I can confirm that downgrading to 2.40.1, with my same codebase, it works as expected.

My codebase is quite simple:

```php
$period = CarbonPeriod::between($start, $end)->filter('isWeekday');
```

@kylekatarnls maybe you have to reopen the issue.

**Comment by kylekatarnls** [comment] 2021-02-02 11:56
I tried your code with 2.44.0 on https://try-carbon.herokuapp.com/

```php
$start = Carbon::parse('2020-12-20');
$end = Carbon::parse('2020-12-29');

foreach (CarbonPeriod::between($start, $end)->filter('isWeekday') as $date) {
  echo "$date\n";
}
```

And it does not throw any exception.

Please provide a minimum standalone code chunk (set the variable so I don't have to take assertions that may change the output) that allows me to reproduce from a scratch setup (like in https://try-carbon.herokuapp.com/)

**Comment by makurtu** [comment] 2021-02-02 12:45
Be aware that if `ty-carbon` heroku app doesn't show Excpetions, maybe we aren't aware of this.
Keep in mind that Carbon works as expected, but if you are debugging your code, it stops everytime on this Exception.

Debugger stops at the line pointed in my first comment.

**Comment by kylekatarnls** [comment] 2021-02-02 12:59
I see, it's likely related to #2201 so. Debbuger calls `__debugInfo()` at each step so even when the date is not initialized.

**Comment by kylekatarnls** [comment] 2021-02-02 13:02
I played a bit around with the debugger but did not reproduce, can you tell where to put the breakpoint or what step in/out path to take?

**Comment by makurtu** [comment] 2021-02-02 13:17
Mmmm I will try to do a small PoC of this issue with Laravel, give me some time, maybe tomorrow will do it.

My current setup is:

* Laravel 7.30
* Carbon: 2.44
* PHP: 8.0.1
* Locale: Catalan

I have this on my `AppServiceProvider.php`:
```php
App::setLocale(app()->getLocale());
\Carbon\Carbon::setLocale(LC_TIME, app()->getLocale());
```

**Comment by kylekatarnls** [comment] 2021-02-02 17:28
OK, but at which step does it trigger the error? I need to know where to put the breakpoint to reproduce it. `__debugInfo()` might be called at a precise moment on which `$this->locale` is not defined but I need to know which one.

**Comment by makurtu** [comment] 2021-02-03 08:03
My call stack on this exception is this:

![image](https://user-images.githubusercontent.com/2920935/106715694-b7d12380-65fd-11eb-8b4a-cf29aa702b28.png)

The error on my code happens when in line 2 of this code (`foreach`):

```php
$period = CarbonPeriod::between($start, $end)->filter('isWeekday');
foreach ($period as $date) {
    ...
    ...
}
```

I'm testing it now with Carbon version `2.44.0`.

**Comment by kylekatarnls** [comment] 2021-02-03 10:06
I just realize you have `\Carbon\Carbon::setLocale(LC_TIME, app()->getLocale());`
It's not related but `LC_TIME` here makes no sense. `setLocale` takes only one argument: the locale.

Else as you can see, I used the same code (and ran it on both PHP 7.4 and 8.0, I also tried in Catalan just in case) with breakpoints at every line.
![image](https://user-images.githubusercontent.com/5966783/106729328-a1cb5f00-660d-11eb-8779-1a40a8b91c4f.png)

And it passes smoothly.

So my very question was, did you enter (step into) at any breakpoint? Because it can behave different and it won't appear in the exception stack trace.

I need a reproducible way so outside the context of your application and with given static data.

**Comment by makurtu** [comment] 2021-02-03 11:25
Updated a PoC of this Exception here: https://github.com/makurtu/poc-carbon

And a GIF:
![PoC-Carbon](https://user-images.githubusercontent.com/2920935/106740399-a3e7ea80-661a-11eb-9b45-36358cdd54b7.gif)

**Comment by kylekatarnls** [comment] 2021-02-03 16:09
Still no bug for me with this project. I use XDebug 3.0.2? What is yours?

**Comment by makurtu** [comment] 2021-02-03 18:20
> Still no bug for me with this project. I use XDebug 3.0.2. What is your debugger?

I also have XDebug 3.0.2, tomorrow I will paste my xdebug config.

**Comment by kylekatarnls** [comment] 2021-02-03 20:42
Maybe it's in the way the IDE try to retrieve the properties. With your example, If I put a breakpoint in Options.php on `$this->$property` it pass the point with "locale" but just don't throw exception on it.

**Comment by kylekatarnls** [comment] 2021-02-03 20:55
Can you try to require `"nesbot/carbon": "dev-fix/issue-2217-mute-getter"` to see if catching the exception is enough? Thanks.

**Comment by makurtu** [comment] 2021-02-04 07:11
Unfortunately, new changes aren't enought :disappointed: 

I will try to dig a little on this, so there is my xdebug config:

```
zend_extension=xdebug
xdebug.mode=debug
xdebug.client_port=9003
xdebug.client_host=127.0.0.1
xdebug.start_with_request=yes
xdebug.discover_client_host=1
xdebug.max_nesting_level=250
xdebug.var_display_max_depth=10
xdebug.log_level = 0
```

**Comment by makurtu** [comment] 2021-02-04 08:12
Finally got it! See this PR: https://github.com/briannesbitt/Carbon/pull/2276

**Comment by kylekatarnls** [comment] 2021-02-04 08:23
> new changes aren't enought

Can you be more precise? What's the outcome? I don't understand how the exception could still be thrown since it's caught.

**Comment by makurtu** [comment] 2021-02-04 08:55
Yes, Exceptions is catched and Carbon can continue running as expected, but Exception is fired and so, debugger stops.

**Comment by makurtu** [comment] 2021-02-04 09:02
Well, disabling XDebug to stop on Exceptions makes this issue solved. Obviously if anyone have Xdebug configured on catching exceptions, this issue will raise again.

**Comment by kylekatarnls** [comment] 2021-02-04 09:15
Ha, so it didn't actually stop the debugging, it just paused it right?

Then is it different from the behavior with `"nesbot/carbon": "2.44.0"`? I mean your initial issue was debugger pausing or stopping?

**Comment by kylekatarnls** [comment] 2021-02-04 09:47
I see the try-catch in `getSettings()` is pointless, as `__isset` which actually try-catch it already is in your stack trace. Sure there are always better solutions than try-catch. But setting debugger to stop (or even pause) on exception even if caught seems unusable to me. Those kind of setting are mostly a last-resort temporary solution if you suspect some generic try-catch (catching all `\Exception` or all `\Throwable`) to hide something. But here the __isset can only catch `\Carbon\Exceptions\UnknownGetterException` which is very specific to the `Carbon` getter, it's not ideal, but still legit.

**Comment by makurtu** [comment] 2021-02-04 10:42
> Ha, so it didn't actually stop the debugging, it just paused it right?
> 
> Then is it different from the behavior with `"nesbot/carbon": "2.44.0"`? I mean your initial issue was debugger pausing or stopping?

Yes, mi issue was that my debugger pauses on exception, i think that when you raise an exception is because an "anormality" was caught, and my "anormality" is that `locale` prop aren't a propperty of `$this` when checking for the prop ([here](https://github.com/briannesbitt/Carbon/blob/a417de2608d14c0598991d1267396d2fd4b7c183/src/Carbon/Traits/Options.php#L416)).

Btw I can configure my Xdebug to stop only on errors and not on exceptions :+1:

**Comment by kylekatarnls** [comment] 2021-02-04 10:53
You can try to pull the last commit on `"nesbot/carbon": "dev-fix/issue-2217-mute-getter"`, I refactored to not use exception as it's a good thing anyway in this case. So you should not longer have your debugger pausing with this change.

But:

> my debugger paused on exception

We can't consider this as an issue. Throwing an exception is not a bug, it tells "You can't do that".

This is not an anomaly. Here this is an expected exception. And try-catch is an existing PHP tool, so you should not expect all your included libraries not to use it. That's meant for what its name literally describe: to try something.

Try to get "locale" => "You can't do that" => OK, not a problem I have an alternative solution. And as long as it's specific scoped exception types, this is actually library business user-land tools should not care about/interfere with.

So Carbon will fix this particular case on the next version, but be warned, similar caught exceptions may legitimately occur from other places and also from many other libraries we/you may include.

**Closed** 2021-02-04 11:06 UTC
