### ISSUE TITLE
Error in calculating previous/next months

### ISSUE THREAD

**Issue by terion-name** [briannesbitt/Carbon#627] opened 2016-03-06 22:09 UTC
```
$month = new Carbon('2016-05');
$month-> endOfMonth(); // updated
[
'month' => $month,
'monthPrev' => $month->copy()->subMonth(),
'monthNext' => $month->copy()->addMonth(),
]
```

Dump:

```
  "month" => Carbon {#233 ▼
    +"date": "2016-05-31 23:59:59.000000"
    +"timezone_type": 3
    +"timezone": "UTC"
  }
  "monthPrev" => Carbon {#241 ▼
    +"date": "2016-05-01 23:59:59.000000"
    +"timezone_type": 3
    +"timezone": "UTC"
  }
  "monthNext" => Carbon {#234 ▼
    +"date": "2016-07-01 23:59:59.000000"
    +"timezone_type": 3
    +"timezone": "UTC"
  }
```

**Comment by lucasmichot** [comment] 2016-03-07 08:34
@terion-name how can your `$month` produce `2016-05-31 23:59:59.000000` ?

```php
<?php

require __DIR__.'/vendor/autoload.php';

use Carbon\Carbon;

$month = new Carbon('2016-05');

print_r([
    'month'     => $month,
    'monthPrev' => $month->copy()->subMonth(),
    'monthNext' => $month->copy()->addMonth(),
]);
```

```sh
Array
(
    [month] => Carbon\Carbon Object
        (
            [date] => 2016-05-01 00:00:00.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

    [monthPrev] => Carbon\Carbon Object
        (
            [date] => 2016-04-01 00:00:00.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

    [monthNext] => Carbon\Carbon Object
        (
            [date] => 2016-06-01 00:00:00.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

)
```

**Comment by terion-name** [comment] 2016-03-07 09:46
@lucasmichot I don't know, but this is how it works.
The code is run in vagrant box with php 7.0.1, carbon version is 1.21.0.
Maybe php version affects?

**Comment by terion-name** [comment] 2016-03-07 09:49
@lucasmichot oh, I see. There was `endOfMonth()` call in the code so it moved the point to end. But in any case there is an error in calculation

**Comment by lucasmichot** [comment] 2016-03-07 09:55
This is the way datetime works:
`2016-05-31` minus one month `2016-04-31`, nevertheless there is only 30 days in April, so logically the date is `2016-05-01`

I think this should be fixed anyway

**Comment by lucasmichot** [comment] 2016-03-07 09:57
Did you try with `addMonthNoOverflow` @terion-name ?

**Comment by terion-name** [comment] 2016-03-07 10:01
@lucasmichot checked — it seems to work correctly, both `addMonthNoOverflow` and `subMonthNoOverflow`. But there is no single word about this method in docs :) And in any case, should be this the default behaviour of `subMonth/addMonth`? When you call `addMonth` you expect it exactly a month to be added, not just 30 days

**Comment by dereuromark** [comment] 2016-03-07 10:05
@terion-name I think so, too. This was already discussed https://github.com/briannesbitt/Carbon/issues/529 and more importantly https://github.com/briannesbitt/Carbon/issues/428 .
It would be a breaking change thus nothing happened.
But I totally agree, the PHP internal way is wrong IMO, the intuitive overflow should be the default.
This was fixed in Chronos by the way for this specific reason.

**Comment by lucasmichot** [comment] 2016-03-07 10:07
This should be addressed in version `2.x` @briannesbitt

**Comment by terion-name** [comment] 2016-03-07 10:13
Yes, it would be a breaking change.. Well, while it is not possible to change behaviour for `1.x`, can you please add `addMonthNoOverflow` and `subMonthNoOverflow` to the docs?

**Comment by lucasmichot** [comment] 2016-03-07 10:15
We're not maintainers of this repo @terion-name 
But I suppose you can PR against `gh-pages` branch

**Comment by joshuaziering** [comment] 2016-03-30 01:56
+1 for this feature.

Today is 3/31 for example. I do a sub month, which is 30 and get March 1. Then, because of leap years, I do sub month and get 1/31.

I would call this "not working as expected"

**Comment by lucasmichot** [comment] 2016-05-12 07:06
Thougts @briannesbitt ?

**Comment by mattmerrill** [comment] 2016-07-13 17:39
+1. Just ran into this as well. Agree that add/subMonthNoOverflow would be the expected behavior

**Comment by lucasmichot** [comment] 2016-07-14 08:36
#710 can solve this, by setting an _non-overflow behaviour_

**Comment by lucasmichot** [comment] 2017-01-16 14:35
Closed by #710

**Closed by lucasmichot** 2017-01-16 14:35 UTC

**Comment by mariavilaro** [comment] 2018-01-02 07:53
Hi, I'm here from the future, and just ran into this the hard way. Please can you mention add/subMonthNoOverflow in the docs? Thank you a lot!

**Comment by inigopascall** [comment] 2020-12-31 13:51
Yeah, and I've just arrived here, also the hard, bumpy way, another 3 years down the line.... for the love of god, please get this added to the docs!

**Comment by kylekatarnls** [comment] 2020-12-31 13:59
This is in the doc for years. RTFM.

**Comment by kylekatarnls** [comment] 2020-12-31 14:04
For the record, native PHP just does the same when you do: `$dateTime->modify('+1 month')` and the PHP doc warns about overflow:
https://www.php.net/manual/en/datetime.modify.php#example-2519

Please just stop complaining, some months have more days than others, and we're not responsible for that.
