### ISSUE TITLE
Update of symfony/translation breaks Carbon

### ISSUE THREAD

**Issue by ehben83** [briannesbitt/Carbon#2466] opened 2021-09-28 09:31 UTC
Hello,

I encountered an issue :
```
Class 'Symfony\Component\Translation\Loader\ArrayLoader' not found
```

in : 
```
vendor/nesbot/carbon/src/Carbon/Translator.php:80
```

since the new version of Symfony/Translate (5.3.8).

Carbon version: **2.53.1**

PHP version: **7.4.24**

Thanks!

**Comment by Machecek** [comment] 2021-09-28 09:37
+1 
Working properly with symfony/translation: v5.3.7, but not with v5.3.8

**Comment by poplach** [comment] 2021-09-28 09:37
Same here, PHP 8.0, Carbon version 2.53.1
Installed new laravel project with errors.

**Comment by foag** [comment] 2021-09-28 09:38
+1 
Upgrading existing project and everything went 💥

**Comment by sinnbeck** [comment] 2021-09-28 09:44
New minor version of the symfony/translator package, which moved the namespace

**Comment by efureev** [comment] 2021-09-28 09:45
We're waiting..... =)

**Comment by simoneargi** [comment] 2021-09-28 09:47
+1
laravel8
php 7.4.1

Did composer update and all broke up

**Comment by poplach** [comment] 2021-09-28 09:47
created a pull request #2467

**Comment by foag** [comment] 2021-09-28 09:51
> created a pull request #2467

That's a very temporary fix. Looks like Symfony is on to a fix, this is not a Carbon bug. https://github.com/symfony/symfony/issues/43212#issuecomment-929029937

**Comment by geekonthepc** [comment] 2021-09-28 09:51
+1

**Comment by afiqiqmal** [comment] 2021-09-28 09:55
Composer update suddenly break.. Git stash 😅

**Comment by kylekatarnls** [comment] 2021-09-28 10:03
Hello guys, +1 and redundant messages help no one. Symfony declares a class from a file path where composer autoload can't find it, the only think we could do from our side is to manually `include()` those files. => We won't do that. you can do it on your project as a quick fix but I just recommend you require `"symfony/translation": "^5.3.7 !=5.3.8"` so you stay on 5.3.7 and will get 5.3.9 (which very likely will fix the regression as this is an obvious unintended breaking change from Symfony side).

There is nothing else to do that just not install this broken version of Symfony and this is not a Carbon bug, so nothing to wait from here, watch the Symfony issue instead: https://github.com/symfony/symfony/issues/43212

**Comment by raftalks** [comment] 2021-09-28 10:03
broke the internet

**Comment by it-can** [comment] 2021-09-28 10:11
seems that ArrayLoader is moved to ```Translation\ArrayLoader```

**Comment by heychazza** [comment] 2021-09-28 10:14
I just had the same issue, haha, I thought I was going crazy..

![image](https://user-images.githubusercontent.com/47271716/135068409-82523a54-cac8-49a2-9a97-e9fd0a046ae2.png)

**Comment by SergMyasnikov** [comment] 2021-09-28 10:15
+1

**Comment by RSickenberg** [comment] 2021-09-28 10:15
Guys, read @kylekatarnls ..!

**Comment by RSickenberg** [comment] 2021-09-28 10:25
It's fixed guys 🎉
https://github.com/symfony/symfony/issues/43212#issuecomment-929059604

**Comment by heychazza** [comment] 2021-09-28 10:26
Can confirm, works perfectly now!

**Comment by kylekatarnls** [comment] 2021-09-28 10:29
Yes fixed in 4.4.32 and 5.3.9.

**Closed by kylekatarnls** 2021-09-28 10:29 UTC

**Comment by iamAKVR** [comment] 2021-12-06 13:56
Just run
composer require symfony/translation:5.3.7 --with-all-dependencies --ignore-platform-reqs

**Comment by kylekatarnls** [comment] 2021-12-06 15:09
Which issue are your trying to solve with this command?

I would not recommend anyone to downgrade symfony/translation. It just postpone problems to later.

Last version of Carbon 2.55.2 supports `^3.4 || ^4.0 || ^5.0 || ^6.0` so you should be able to use the latest stable version, currently 5.4.0 or 6.0.0 of Symfony with no issue.

**Comment by mattdillon-genie** [comment] 2023-12-18 22:55
This is again happening with Symfony 7.x and Carbon 2.x. I can see that Carbon 3 is going to support Symfony ^7.0. Is there an expected release date for this?

**Comment by kylekatarnls** [comment] 2023-12-19 07:44
It should happen in January, but you can already use it: `composer require nesbot/carbon:^3@dev`
