### ISSUE TITLE
createFromTime creates objects with different dates

### ISSUE THREAD

**Issue by serg-mo** [briannesbitt/Carbon#983] opened 2017-08-01 02:09 UTC
Steps to reproduce
```
$time_zone = "America/Los_Angeles";

$morning = Carbon::createFromTime(7, 0, 0, $time_zone);
$evening = Carbon::createFromTime(19, 0, 0, $time_zone);
$now = Carbon::now($time_zone);
echo $morning."\n".$evening."\n".$now."\n";

date_default_timezone_set($time_zone);
$morning = Carbon::createFromTime(7, 0, 0, $time_zone);
$evening = Carbon::createFromTime(19, 0, 0, $time_zone);
$now = Carbon::now($time_zone);
echo $morning."\n".$evening."\n".$now."\n";
```

**Comment by Glavic** [comment] 2018-02-13 20:15
Both examples are the same, so are the results. 
What seem to be an issue here?

**Comment by serg-mo** [comment] 2018-02-13 20:26
Hmm, it's working for me now, but at the time this code produced different results. Maybe it's related to DST or default timezone? I can't reproduce it now.

**Comment by Glavic** [comment] 2018-02-13 20:35
`Carbon.php` was not changed from `2017-05-11`: https://github.com/briannesbitt/Carbon/commits/master/src/Carbon/Carbon.php 
Your issue is from `2017-08-01`: based on that, nothing has changed in code since your issue.

Like I said, both examples are same, whatever timezone you used. Probably you tested (bug'ed) code is different from one you have posted?

Nevertheless, since problem cannot be reproduced, I will close this issue. If anything similar happens, please comment bellow, and I will reopen the issue.

**Comment by LastDragon-ru** [comment] 2018-02-14 06:47
@Glavic, please reopen this. Bug exists! When you call `Carbon::createFromTime()`, it call `return static::create(null, null, null, $hour, $minute, $second, $tz)`, but `create` do this
 
```
$defaults = array_combine(array(
            'year',
            'month',
            'day',
            'hour',
            'minute',
            'second',
        ), explode('-', date('Y-n-j-G-i-s', $now)));
```

And as you can see `$defaults` totally ignores `$tz` and can returns invalid day. But this depends on time and $tz - this is why bug is not always reproduced. To reproduce you should wait (or change machine time) until ~14:00 (UTC) and call `createFromTime()` with `Pacific/Kiritimati` (GMT+14)  timezone - you get today instead (14 feb 2018) of tomorrow (15 feb)

**Comment by kylekatarnls** [comment] 2018-02-14 08:07
`$tz` is not in the `$defaults` but it is passed to the create:

```php
$instance = static::createFromFormat('Y-n-j G:i:s', sprintf('%s-%s-%s %s:%02s:%02s', $year, $month, $day, $hour, $minute, $second), $tz);
```
Here the last argument, and it is how we should pass the timezone. I will try to reproduce this.

**Comment by LastDragon-ru** [comment] 2018-02-14 08:20
> I will try to reproduce this.

```
    $tz   = 'GMT+25';
    $now  = Carbon::now($tz); 
    $date = Carbon::createFromTime($now->hour, $now->minute, $now->second, $tz);
```

```
{
   "now":"2018-02-15T09:17:46+25:00",
    "invalid":"2018-02-14T09:17:46+25:00"
}
```

**Comment by Glavic** [comment] 2018-02-14 09:00
@LastDragon-ru: are you testing this in tests? Can you disable test date? Add `Carbon::setTestNow();` at the beginning.

**Comment by Glavic** [comment] 2018-02-14 09:02
`date()` function should have no business doing in Carbon library. I removed it: https://github.com/Glavic/Carbon/commit/3f12b85dc6ab0fb1ea343d2783bada0d793379db
Could you test it now?

**Comment by LastDragon-ru** [comment] 2018-02-14 09:08
> are you testing this in tests?
Yes.

> Could you test it now?
Sure, I will check, but at evening.

**Comment by LastDragon-ru** [comment] 2018-02-15 07:05
I tested it on my code where is this bug was found and seems all works now. Thank you for fix.

**Comment by kylekatarnls** [comment] 2018-02-15 08:24
Glad to hear that :)

**Closed by kylekatarnls** 2018-02-15 08:24 UTC
Labels: need investigation
