### ISSUE TITLE
 Class 'Carbon\Translator' not found  

### ISSUE THREAD

**Issue by ngoyal16** [briannesbitt/Carbon#2514] opened 2021-12-03 12:24 UTC
Hello,

Carbon version: 2.55.0

PHP version: 7.4

In Localization.php line 696:
                                       
  Class 'Carbon\Translator' not found  
                                       

Thanks!

**Comment by sirvantos** [comment] 2021-12-03 12:25
same ->  php7.4 +  Laravel 7

**Comment by stanimirdim92** [comment] 2021-12-03 12:27
Same.

**Comment by it-can** [comment] 2021-12-03 12:50
Larave 8, php 8 also

```
 Error

  Class "Carbon\Translator" not found

  at vendor/nesbot/carbon/src/Carbon/Traits/Localization.php:696
    692▕      */
    693▕     protected static function translator()
    694▕     {
    695▕         if (static::$translator === null) {
  ➜ 696▕             static::$translator = Translator::get();
    697▕         }
    698▕
    699▕         return static::$translator;
    700▕     }

      +11 vendor frames
  12  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Carbon\Laravel\ServiceProvider))

      +5 vendor frames
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by kylekatarnls** [comment] 2021-12-03 13:03
Hello, can you try to `composer require nesbot/carbon:dev-fix/translator-out`? If you can confirm it helps, I will release this patch as `2.55.1`

**Comment by it-can** [comment] 2021-12-03 13:11
As far as I can test quickly still the same errror..

**Comment by kylekatarnls** [comment] 2021-12-03 13:45
I still need the complete list of steps to reproduce. Right now I have carbon installed in Laravel apps and translation working fine with 2.55.0. So there is a particular setup or way to install dependency, maybe file caching issue that make this happen.

**Comment by it-can** [comment] 2021-12-03 13:51
All my Laravel apps are b*tching with this error, running php 8.0.13, laravel 8.74.0. I cleared caches on composer and removed the vendor folder. But nothing helps...

Did you also try composer with optimize autoloader?

**Comment by X-Coder264** [comment] 2021-12-03 13:54
When running composer update to Carbon 2.55.0 I got in the output:

```
Class Carbon\Translator located in ./vendor/nesbot/carbon/src/Carbon/TranslatorStrongType.php does not comply with psr-4 autoloading standard. Skipping.
Class Carbon\Translator located in ./vendor/nesbot/carbon/src/Carbon/TranslatorWeakType.php does not comply with psr-4 autoloading standard. Skipping.
```

Updating Carbon to `dev-master` - there's no such output in Composer update command anymore.

**Comment by it-can** [comment] 2021-12-03 13:55
I get this error also if I install a new Laravel project

```
laravel new testje

 _                               _
| |                             | |
| |     __ _ _ __ __ ___   _____| |
| |    / _` | '__/ _` \ \ / / _ \ |
| |___| (_| | | | (_| |\ V /  __/ |
|______\__,_|_|  \__,_| \_/ \___|_|

Creating a "laravel/laravel" project at "./testje"
Installing laravel/laravel (v8.6.8)
  - Downloading laravel/laravel (v8.6.8)
  - Installing laravel/laravel (v8.6.8): Extracting archive
Created project in /Users/mvugteveen/Desktop/testje
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies
Lock file operations: 110 installs, 0 updates, 0 removals
  - Locking asm89/stack-cors (v2.0.3)
  - Locking brick/math (0.9.3)
  - Locking dflydev/dot-access-data (v3.0.1)
  - Locking doctrine/inflector (2.0.4)
  - Locking doctrine/instantiator (1.4.0)
  - Locking doctrine/lexer (1.2.1)
  - Locking dragonmantank/cron-expression (v3.1.0)
  - Locking egulias/email-validator (2.1.25)
  - Locking facade/flare-client-php (1.9.1)
  - Locking facade/ignition (2.17.2)
  - Locking facade/ignition-contracts (1.0.2)
  - Locking fakerphp/faker (v1.16.0)
  - Locking filp/whoops (2.14.4)
  - Locking fruitcake/laravel-cors (v2.0.4)
  - Locking graham-campbell/result-type (v1.0.4)
  - Locking guzzlehttp/guzzle (7.4.0)
  - Locking guzzlehttp/promises (1.5.1)
  - Locking guzzlehttp/psr7 (2.1.0)
  - Locking hamcrest/hamcrest-php (v2.0.1)
  - Locking laravel/framework (v8.74.0)
  - Locking laravel/sail (v1.12.9)
  - Locking laravel/sanctum (v2.12.2)
  - Locking laravel/serializable-closure (v1.0.5)
  - Locking laravel/tinker (v2.6.2)
  - Locking league/commonmark (2.0.2)
  - Locking league/config (v1.1.1)
  - Locking league/flysystem (1.1.8)
  - Locking league/mime-type-detection (1.9.0)
  - Locking mockery/mockery (1.4.4)
  - Locking monolog/monolog (2.3.5)
  - Locking myclabs/deep-copy (1.10.2)
  - Locking nesbot/carbon (2.55.1)
  - Locking nette/schema (v1.2.2)
  - Locking nette/utils (v3.2.6)
  - Locking nikic/php-parser (v4.13.2)
  - Locking nunomaduro/collision (v5.10.0)
  - Locking opis/closure (3.6.2)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.1.0)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.3.0)
  - Locking phpdocumentor/type-resolver (1.5.1)
  - Locking phpoption/phpoption (1.8.0)
  - Locking phpspec/prophecy (1.14.0)
  - Locking phpunit/php-code-coverage (9.2.9)
  - Locking phpunit/php-file-iterator (3.0.6)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking phpunit/phpunit (9.5.10)
  - Locking psr/container (1.1.2)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/log (2.0.0)
  - Locking psr/simple-cache (1.0.1)
  - Locking psy/psysh (v0.10.12)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking ramsey/collection (1.2.2)
  - Locking ramsey/uuid (4.2.3)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.3)
  - Locking sebastian/exporter (4.0.4)
  - Locking sebastian/global-state (5.0.3)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (2.3.4)
  - Locking sebastian/version (3.0.2)
  - Locking swiftmailer/swiftmailer (v6.3.0)
  - Locking symfony/console (v5.4.0)
  - Locking symfony/css-selector (v5.4.0)
  - Locking symfony/deprecation-contracts (v2.5.0)
  - Locking symfony/error-handler (v5.4.0)
  - Locking symfony/event-dispatcher (v6.0.0)
  - Locking symfony/event-dispatcher-contracts (v3.0.0)
  - Locking symfony/finder (v5.4.0)
  - Locking symfony/http-foundation (v5.4.0)
  - Locking symfony/http-kernel (v5.4.0)
  - Locking symfony/mime (v5.4.0)
  - Locking symfony/polyfill-ctype (v1.23.0)
  - Locking symfony/polyfill-iconv (v1.23.0)
  - Locking symfony/polyfill-intl-grapheme (v1.23.1)
  - Locking symfony/polyfill-intl-idn (v1.23.0)
  - Locking symfony/polyfill-intl-normalizer (v1.23.0)
  - Locking symfony/polyfill-mbstring (v1.23.1)
  - Locking symfony/polyfill-php72 (v1.23.0)
  - Locking symfony/polyfill-php73 (v1.23.0)
  - Locking symfony/polyfill-php80 (v1.23.1)
  - Locking symfony/polyfill-php81 (v1.23.0)
  - Locking symfony/process (v5.4.0)
  - Locking symfony/routing (v5.4.0)
  - Locking symfony/service-contracts (v2.5.0)
  - Locking symfony/string (v6.0.0)
  - Locking symfony/translation (v6.0.0)
  - Locking symfony/translation-contracts (v3.0.0)
  - Locking symfony/var-dumper (v5.4.0)
  - Locking theseer/tokenizer (1.2.1)
  - Locking tijsverkoyen/css-to-inline-styles (2.2.3)
  - Locking vlucas/phpdotenv (v5.4.0)
  - Locking voku/portable-ascii (1.5.6)
  - Locking webmozart/assert (1.10.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 110 installs, 0 updates, 0 removals
  - Downloading doctrine/inflector (2.0.4)
  - Downloading doctrine/lexer (1.2.1)
  - Downloading symfony/polyfill-ctype (v1.23.0)
  - Downloading webmozart/assert (1.10.0)
  - Downloading dragonmantank/cron-expression (v3.1.0)
  - Downloading symfony/polyfill-php80 (v1.23.1)
  - Downloading symfony/polyfill-mbstring (v1.23.1)
  - Downloading symfony/var-dumper (v5.4.0)
  - Downloading symfony/polyfill-intl-normalizer (v1.23.0)
  - Downloading symfony/polyfill-intl-grapheme (v1.23.1)
  - Downloading symfony/string (v6.0.0)
  - Downloading symfony/deprecation-contracts (v2.5.0)
  - Downloading psr/container (1.1.2)
  - Downloading symfony/service-contracts (v2.5.0)
  - Downloading symfony/polyfill-php73 (v1.23.0)
  - Downloading symfony/console (v5.4.0)
  - Downloading psr/log (2.0.0)
  - Downloading monolog/monolog (2.3.5)
  - Downloading voku/portable-ascii (1.5.6)
  - Downloading phpoption/phpoption (1.8.0)
  - Downloading graham-campbell/result-type (v1.0.4)
  - Downloading vlucas/phpdotenv (v5.4.0)
  - Downloading symfony/css-selector (v5.4.0)
  - Downloading tijsverkoyen/css-to-inline-styles (2.2.3)
  - Downloading symfony/routing (v5.4.0)
  - Downloading symfony/process (v5.4.0)
  - Downloading symfony/polyfill-php72 (v1.23.0)
  - Downloading symfony/polyfill-intl-idn (v1.23.0)
  - Downloading symfony/mime (v5.4.0)
  - Downloading symfony/http-foundation (v5.4.0)
  - Downloading psr/event-dispatcher (1.0.0)
  - Downloading symfony/event-dispatcher-contracts (v3.0.0)
  - Downloading symfony/event-dispatcher (v6.0.0)
  - Downloading symfony/error-handler (v5.4.0)
  - Downloading symfony/http-kernel (v5.4.0)
  - Downloading symfony/finder (v5.4.0)
  - Downloading symfony/polyfill-iconv (v1.23.0)
  - Downloading egulias/email-validator (2.1.25)
  - Downloading swiftmailer/swiftmailer (v6.3.0)
  - Downloading symfony/polyfill-php81 (v1.23.0)
  - Downloading ramsey/collection (1.2.2)
  - Downloading brick/math (0.9.3)
  - Downloading ramsey/uuid (4.2.3)
  - Downloading psr/simple-cache (1.0.1)
  - Downloading opis/closure (3.6.2)
  - Downloading symfony/translation-contracts (v3.0.0)
  - Downloading symfony/translation (v6.0.0)
  - Downloading league/mime-type-detection (1.9.0)
  - Downloading league/flysystem (1.1.8)
  - Downloading nette/utils (v3.2.6)
  - Downloading nette/schema (v1.2.2)
  - Downloading dflydev/dot-access-data (v3.0.1)
  - Downloading league/config (v1.1.1)
  - Downloading league/commonmark (2.0.2)
  - Downloading laravel/serializable-closure (v1.0.5)
  - Downloading laravel/framework (v8.74.0)
  - Downloading facade/ignition-contracts (1.0.2)
  - Downloading facade/flare-client-php (1.9.1)
  - Downloading facade/ignition (2.17.2)
  - Downloading fakerphp/faker (v1.16.0)
  - Downloading asm89/stack-cors (v2.0.3)
  - Downloading fruitcake/laravel-cors (v2.0.4)
  - Downloading psr/http-message (1.0.1)
  - Downloading psr/http-client (1.0.1)
  - Downloading ralouphie/getallheaders (3.0.3)
  - Downloading psr/http-factory (1.0.1)
  - Downloading guzzlehttp/psr7 (2.1.0)
  - Downloading guzzlehttp/promises (1.5.1)
  - Downloading guzzlehttp/guzzle (7.4.0)
  - Downloading laravel/sail (v1.12.9)
  - Downloading laravel/sanctum (v2.12.2)
  - Downloading nikic/php-parser (v4.13.2)
  - Downloading psy/psysh (v0.10.12)
  - Downloading laravel/tinker (v2.6.2)
  - Downloading hamcrest/hamcrest-php (v2.0.1)
  - Downloading mockery/mockery (1.4.4)
  - Downloading filp/whoops (2.14.4)
  - Downloading nunomaduro/collision (v5.10.0)
  - Downloading phpdocumentor/reflection-common (2.2.0)
  - Downloading phpdocumentor/type-resolver (1.5.1)
  - Downloading phpdocumentor/reflection-docblock (5.3.0)
  - Downloading sebastian/version (3.0.2)
  - Downloading sebastian/type (2.3.4)
  - Downloading sebastian/resource-operations (3.0.3)
  - Downloading sebastian/recursion-context (4.0.4)
  - Downloading sebastian/object-reflector (2.0.4)
  - Downloading sebastian/object-enumerator (4.0.4)
  - Downloading sebastian/global-state (5.0.3)
  - Downloading sebastian/exporter (4.0.4)
  - Downloading sebastian/environment (5.1.3)
  - Downloading sebastian/diff (4.0.4)
  - Downloading sebastian/comparator (4.0.6)
  - Downloading sebastian/code-unit (1.0.8)
  - Downloading sebastian/cli-parser (1.0.1)
  - Downloading phpunit/php-timer (5.0.3)
  - Downloading phpunit/php-text-template (2.0.4)
  - Downloading phpunit/php-invoker (3.1.1)
  - Downloading phpunit/php-file-iterator (3.0.6)
  - Downloading theseer/tokenizer (1.2.1)
  - Downloading sebastian/lines-of-code (1.0.3)
  - Downloading sebastian/complexity (2.0.2)
  - Downloading sebastian/code-unit-reverse-lookup (2.0.3)
  - Downloading phpunit/php-code-coverage (9.2.9)
  - Downloading doctrine/instantiator (1.4.0)
  - Downloading phpspec/prophecy (1.14.0)
  - Downloading phar-io/version (3.1.0)
  - Downloading phar-io/manifest (2.0.3)
  - Downloading myclabs/deep-copy (1.10.2)
  - Downloading phpunit/phpunit (9.5.10)
  - Installing doctrine/inflector (2.0.4): Extracting archive
  - Installing doctrine/lexer (1.2.1): Extracting archive
  - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing dragonmantank/cron-expression (v3.1.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.23.1): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.23.1): Extracting archive
  - Installing symfony/var-dumper (v5.4.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.23.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.23.1): Extracting archive
  - Installing symfony/string (v6.0.0): Extracting archive
  - Installing symfony/deprecation-contracts (v2.5.0): Extracting archive
  - Installing psr/container (1.1.2): Extracting archive
  - Installing symfony/service-contracts (v2.5.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.23.0): Extracting archive
  - Installing symfony/console (v5.4.0): Extracting archive
  - Installing psr/log (2.0.0): Extracting archive
  - Installing monolog/monolog (2.3.5): Extracting archive
  - Installing voku/portable-ascii (1.5.6): Extracting archive
  - Installing phpoption/phpoption (1.8.0): Extracting archive
  - Installing graham-campbell/result-type (v1.0.4): Extracting archive
  - Installing vlucas/phpdotenv (v5.4.0): Extracting archive
  - Installing symfony/css-selector (v5.4.0): Extracting archive
  - Installing tijsverkoyen/css-to-inline-styles (2.2.3): Extracting archive
  - Installing symfony/routing (v5.4.0): Extracting archive
  - Installing symfony/process (v5.4.0): Extracting archive
  - Installing symfony/polyfill-php72 (v1.23.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.23.0): Extracting archive
  - Installing symfony/mime (v5.4.0): Extracting archive
  - Installing symfony/http-foundation (v5.4.0): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.0.0): Extracting archive
  - Installing symfony/event-dispatcher (v6.0.0): Extracting archive
  - Installing symfony/error-handler (v5.4.0): Extracting archive
  - Installing symfony/http-kernel (v5.4.0): Extracting archive
  - Installing symfony/finder (v5.4.0): Extracting archive
  - Installing symfony/polyfill-iconv (v1.23.0): Extracting archive
  - Installing egulias/email-validator (2.1.25): Extracting archive
  - Installing swiftmailer/swiftmailer (v6.3.0): Extracting archive
  - Installing symfony/polyfill-php81 (v1.23.0): Extracting archive
  - Installing ramsey/collection (1.2.2): Extracting archive
  - Installing brick/math (0.9.3): Extracting archive
  - Installing ramsey/uuid (4.2.3): Extracting archive
  - Installing psr/simple-cache (1.0.1): Extracting archive
  - Installing opis/closure (3.6.2): Extracting archive
  - Installing symfony/translation-contracts (v3.0.0): Extracting archive
  - Installing symfony/translation (v6.0.0): Extracting archive
  - Installing nesbot/carbon (2.55.1): Extracting archive
  - Installing league/mime-type-detection (1.9.0): Extracting archive
  - Installing league/flysystem (1.1.8): Extracting archive
  - Installing nette/utils (v3.2.6): Extracting archive
  - Installing nette/schema (v1.2.2): Extracting archive
  - Installing dflydev/dot-access-data (v3.0.1): Extracting archive
  - Installing league/config (v1.1.1): Extracting archive
  - Installing league/commonmark (2.0.2): Extracting archive
  - Installing laravel/serializable-closure (v1.0.5): Extracting archive
  - Installing laravel/framework (v8.74.0): Extracting archive
  - Installing facade/ignition-contracts (1.0.2): Extracting archive
  - Installing facade/flare-client-php (1.9.1): Extracting archive
  - Installing facade/ignition (2.17.2): Extracting archive
  - Installing fakerphp/faker (v1.16.0): Extracting archive
  - Installing asm89/stack-cors (v2.0.3): Extracting archive
  - Installing fruitcake/laravel-cors (v2.0.4): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing guzzlehttp/psr7 (2.1.0): Extracting archive
  - Installing guzzlehttp/promises (1.5.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.4.0): Extracting archive
  - Installing laravel/sail (v1.12.9): Extracting archive
  - Installing laravel/sanctum (v2.12.2): Extracting archive
  - Installing nikic/php-parser (v4.13.2): Extracting archive
  - Installing psy/psysh (v0.10.12): Extracting archive
  - Installing laravel/tinker (v2.6.2): Extracting archive
  - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
  - Installing mockery/mockery (1.4.4): Extracting archive
  - Installing filp/whoops (2.14.4): Extracting archive
  - Installing nunomaduro/collision (v5.10.0): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.5.1): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (2.3.4): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.3): Extracting archive
  - Installing sebastian/exporter (4.0.4): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.9): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (1.14.0): Extracting archive
  - Installing phar-io/version (3.1.0): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phpunit/phpunit (9.5.10): Extracting archive
61 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Class "Carbon\Translator" not found

  at vendor/nesbot/carbon/src/Carbon/Traits/Localization.php:696
    692▕      */
    693▕     protected static function translator()
    694▕     {
    695▕         if (static::$translator === null) {
  ➜ 696▕             static::$translator = Translator::get();
    697▕         }
    698▕
    699▕         return static::$translator;
    700▕     }

      +11 vendor frames
  12  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Carbon\Laravel\ServiceProvider))

      +5 vendor frames
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by sirvantos** [comment] 2021-12-03 13:55
> I still need the complete list of steps to reproduce. Right now I have carbon installed in Laravel apps and translation working fine with 2.55.0. So there is a particular setup or way to install dependency, maybe file caching issue that make this happen.

try this

composer install --no-dev **--classmap-authoritative** --optimize-autoloader

I think --classmap-authoritative  is reason

**Comment by it-can** [comment] 2021-12-03 13:57
> > I still need the complete list of steps to reproduce. Right now I have carbon installed in Laravel apps and translation working fine with 2.55.0. So there is a particular setup or way to install dependency, maybe file caching issue that make this happen.
> 
> try this
> 
> composer install --no-dev **--classmap-authoritative** --optimize-autoloader
> 
> I think --classmap-authoritative is reason

tested this, also get this error

**Comment by andriesreitsma** [comment] 2021-12-03 14:09
```
This option says that if something is not found in the classmap, then it does not exist and the autoloader should not attempt to look on the filesystem according to PSR-4 rules.
```
Seems correct since it uses a trick to load the corresponding Class. Annoyingly it **cannot** be reproduced with an `composer dump-autoload --classmap-authoritative`

**Comment by kylekatarnls** [comment] 2021-12-03 14:10
@X-Coder264 > it's a different issue already fixed in 2.55.1 (and it's a warning, it does not block your installation)

@sirvantos > Thanks 👍 Indeed this is the step that differ and I can reproduce the error with it. I will see why this miss the `Translator` class then I'll add in our CI a test using this option so it will be officially supported in the next release.

**Comment by kylekatarnls** [comment] 2021-12-03 14:15
OK, indeed the doc explains the issue:

> --classmap-authoritative
> This option makes the autoloader always return very quickly. On the flipside it also means that in case a class is generated at runtime for some reason, it will not be allowed to be autoloaded. If your project or any of your dependencies does that then you might experience "class not found" issues in production. Enable this with care.

Due to the impossibility for a translator to be compatible to both Symfony 6 and Symfony > 6, we have to load it on runtime, I will find a way to make composer aware of this.

**Comment by kylekatarnls** [comment] 2021-12-03 14:22
@ngoyal16 > This last one is a different issue. I suspect file cache issue or installing dependencies with a different PHP version that the one used to run it in production can be the cause. If not, can you please open a separated issue with exact steps to reproduce this one. Thanks.

**Comment by andriesreitsma** [comment] 2021-12-03 14:24
@kylekatarnls maybe this helps in a way to get it sorted out:

```php
namespace Carbon;

use ReflectionMethod;
use Symfony\Component\Translation;
use Symfony\Contracts\Translation\TranslatorInterface;

$transMethod = new ReflectionMethod(
    class_exists(TranslatorInterface::class)
        ? TranslatorInterface::class
        : Translation\Translator::class,
    'trans'
);

if($transMethod->hasReturnType()) {
    class SwitchTranslator extends TranslatorStrongType {}
} else {
    class SwitchTranslator extends TranslatorWeakType {}
}

class Translator extends SwitchTranslator {}
```

**Comment by kylekatarnls** [comment] 2021-12-03 14:26
Nice, it would indeed help to have the `Translator` statically created in the file while implementation is made on runtime.

**Comment by kylekatarnls** [comment] 2021-12-03 14:37
This fix can be tested using this in composer.json:
```json
"nesbot/carbon": "dev-fix/support-classmap-authoritative as 2.55.2"
```
It worked fine from there with the `composer install --no-dev --classmap-authoritative --optimize-autoloader` command.

**Closed** 2021-12-03 14:59 UTC

**Comment by kylekatarnls** [comment] 2021-12-03 15:24
2.55.2 released with support for `classmap-authoritative`

**Comment by it-can** [comment] 2021-12-03 15:25
works !!! thanks

**Comment by mfn** [comment] 2021-12-03 15:35
Damn, that surely was no fun to wake up to this.

Big shout out to @kylekatarnls for your diligence, professionalism, patience and awesome hard work. Very much appreciated 🙏🏼 

I chipped in a small contribution so you can end the day and work week maybe with a small smile 🌷
