### ISSUE TITLE
PHP Fatal error:  Class 'CarbonPeriod' not found in Psy Shell code on line 1 [Solved]

### ISSUE THREAD

**Issue by sadalsuud** [briannesbitt/Carbon#1321] opened 2018-05-24 19:34 UTC
When I do in tinker on laravel, $period = new CarbonPeriod('21:00', '2018-04-27'); y got this message error : PHP Fatal error:  Class 'CarbonPeriod' not found in Psy Shell code on line 1

Where is CarbonPeriod?

**Comment by kylekatarnls** [comment] 2018-05-24 19:40
CarbonPeriod is a feature of the shinny new version 1.29. Maybe you need to upgrade Carbon first.

**Comment by peter279k** [comment] 2018-05-25 02:04
According to the [release log](https://github.com/briannesbitt/Carbon/releases), it should use the ```1.29.0``` version.

**Comment by sadalsuud** [comment] 2018-05-25 04:16
Thanks, I do update to Carbon 1.29 as you tell me. And in tinker yet not work, I got this message: 
    PHP Fatal error:  Class 'Carbon/Carbon/CarbonPeriod' not found in Psy Shell code on line 1
but I try into closure and it works!

**Comment by peter279k** [comment] 2018-05-25 04:57
@sadalsuud, thank you for your reply.
I think you use the namespace is incorrect because the ```CarbonPeriod``` tests should be worked well.
You can refer this [CarbonPeriod getter test](https://github.com/briannesbitt/Carbon/blob/master/tests/CarbonPeriod/GettersTest.php) to know how to use CarbonPeriod namespace.
It should ```use Carbon\CarbonPeriod;``` rather than ```Carbon/Carbon/CarbonPeriod;```.

**Comment by kylekatarnls** [comment] 2018-05-25 06:02
If you have `use Carbon\CarbonPeriod` at the top of your file, then just call `CarbonPeriod` in your code. If you don't use namespaces statements, call it with `\Carbon\CarbonPeriod`

**Comment by sadalsuud** [comment] 2018-05-25 22:05
@peter279k well, I write `use Carbon\CarbonPeriod`  but I don't know why the error was "'Carbon/Carbon/CarbonPeriod'" with / rather \ 
Anyway, today It is work in tinker 
`use \Carbon\CarbonPeriod
$periodoLabor = new CarbonPeriod("06:00", "13:00")  
`
Maybe ... restart something fixit

**Comment by kylekatarnls** [comment] 2018-05-27 09:50
I close this. If you can provide us a minimal code to reproduce the bug I would reopen it.

**Closed by kylekatarnls** 2018-05-27 09:50 UTC

**Comment by riotCode** [comment] 2018-05-29 13:17
@sadalsuud laravel/framework is hard set on Carbon `1.25.*`

**Comment by kylekatarnls** [comment] 2018-05-29 13:35
Laravel 5.6 only, Laravel 5.7 allow 1.26+. If you want Laravel 5.6 to support new Carbon features, you can participate here to the discussion: https://github.com/laravel/framework/issues/24335
